### ISSUE TITLE
ERROR: clGetPlatformIDs(-1001)

### ISSUE THREAD

**Issue by randydevitt** [OpenPTrack/open_ptrack#103]
When running `roslaunch kinect2_bridge kinect2_bridge` this error message repeatedly pops up

Running gefore 930m with nvidia 352 drivers

[kinect2_head_kinect2_bridge-2] restarting process
process[kinect2_head_kinect2_bridge-2]: started with pid [10824]
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenCLDepthPacketProcessor::init] ERROR: clGetPlatformIDs(-1001)
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
[kinect2_head_kinect2_bridge-2] process has died [pid 10824, exit code -6, cmd /home/pc7/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge __name:=kinect2_head_kinect2_bridge __log:=/home/pc7/.ros/log/c8cf4442-3e01-11e6-aa30-e728ea441c89/kinect2_head_kinect2_bridge-2.log].
log file: /home/pc7/.ros/log/c8cf4442-3e01-11e6-aa30-e728ea441c89/kinect2_head_kinect2_bridge-2*.log
[kinect2_head_kinect2_bridge-2] restarting process

**Comment by lthursdayl** [comment]
the 940m graphics card has not been tested by us to verify that it is supported per our [deployment guide](https://github.com/OpenPTrack/open_ptrack/wiki/Tested-Hardware). With that said did you run:

```
 cd ~/workspace/ros/catkin/devel/lib/kinect2_bridge
 sudo ./kinect2_bridge
```
before running: 

`roslaunch kinect2_bridge kinect2_bridge.launch`

more information can be found [here](https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide#6-kinect-v2-installation). Did you follow these directions?

**Comment by lthursdayl** [comment]
also, this may solve your error:

delete the open_ptrack folder in /home/[replace with home folder]
 
Now in the terminal:
 
ln –s /home/[replace with home folder]/workspace/ros/catkin/src/open_ptrack  /home/[replace with home folder]
 
then:
 
roscd open_ptrack/../scripts
chmod +x kinect2_install.sh
./kinect2_install.sh


now try running `roslaunch kinect2_bridge kinect2_bridge.launch` again, after running ( this needs to be done after each restart)

 cd ~/workspace/ros/catkin/devel/lib/kinect2_bridge

**Comment by randydevitt** [comment]
For followup as to people who may have the same issue, it is a drivers issue causeed by NVIDIA Optimus. Ideally, the computer you use should not have optimus but in the event it does use NVIDIA prime to try to fix it. For our laptop(dell inspiron with nvidia gtx 960m, our solution ended up being using the following guide to reconfigure our xorg settings after installing nvidia drivers
http://us.download.nvidia.com/XFree86/Linux-x86/319.12/README/randr14.html
The one change made from this document is .xinitrc was changed to .xsessionrc
