### ISSUE TITLE
Invoking "make -j8 -l8" failed

### ISSUE THREAD

**Issue by shakevincent** [OpenPTrack/open_ptrack#104]
When running ./ros_configure.sh
 this error message repeatedly pops up
make[2]: *** [open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/apps/haardispada_nodelet.cpp.o] Error 1
make[1]: *** [open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
I would like to seek everyone's help，thanks

**Comment by nanodust** [comment]
What is your host ?

If it doesn't have 8 cores, that will fail.

**Comment by mmunaro** [comment]
Can you please post the complete error message? That is just the final part.
The number of cores should not be a problem, because the minimum between what asked and what you have is used.

**Comment by shakevincent** [comment]
the complete error message 
[ 98%] Built target swissranger_camera_gencfg
In file included from /home/deeplearning/workspace/ros/catkin/src/freenect_stack/freenect_camera/include/freenect_camera/freenect_driver.hpp:5:0,
                 from /home/deeplearning/workspace/ros/catkin/src/freenect_stack/freenect_camera/src/nodelets/driver.h:54,
                 from /home/deeplearning/workspace/ros/catkin/src/freenect_stack/freenect_camera/src/nodelets/driver.cpp:39:
/home/deeplearning/workspace/ros/catkin/src/freenect_stack/freenect_camera/include/freenect_camera/freenect_device.hpp:11:50: fatal error: libfreenect/libfreenect_registration.h: No such file or directory
compilation terminated.
In file included from /home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:31:0:
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/include/open_ptrack/detection/haardispada.h:63:16: error: 'cv::INTER_AREA' has not been declared
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/include/open_ptrack/detection/haardispada.h:104:9: error: 'CvBoost' does not name a type
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'void open_ptrack::detection::HaarDispAdaClassifier::detect(std::vector<cv::Rect_<int> >&, std::vector<int>&, cv::Mat&, std::vector<cv::Rect_<int> >&, std::vector<int>&, bool)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:83:22: error: 'HDAC_' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'void open_ptrack::detection::HaarDispAdaClassifier::detect(std::vector<cv::Rect_<int> >&, std::vector<int>&, cv::Mat&, std::vector<cv::Rect_<int> >&, std::vector<int>&, std::vector<float>&, bool)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:123:22: error: 'HDAC_' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'void open_ptrack::detection::HaarDispAdaClassifier::train(std::string)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:191:7: error: 'CvBoostParams' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:191:21: error: expected ';' before 'bparams'
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:193:7: error: 'bparams' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:212:44: error: 'CV_VAR_ORDERED' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:214:7: error: 'HDAC_' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:214:29: error: 'CV_ROW_SAMPLE' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'void open_ptrack::detection::HaarDispAdaClassifier::load(std::string)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:283:7: error: 'HDAC_' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'int open_ptrack::detection::HaarDispAdaClassifier::haar_features_fast(cv::Mat&)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:415:7: error: 'resize' is not a member of 'cv'
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:416:7: error: 'resize' is not a member of 'cv'
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'int open_ptrack::detection::HaarDispAdaClassifier::haar_features(cv::Mat&, cv::Mat&)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:470:90: error: 'resize' was not declared in this scope
make[2]: *** [open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/src/haardispada.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/apps/haardispada_nodelet.cpp:40:0:
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/include/open_ptrack/detection/haardispada.h:63:16: error: 'cv::INTER_AREA' has not been declared
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/include/open_ptrack/detection/haardispada.h:104:9: error: 'CvBoost' does not name a type
make[2]: *** [freenect_stack/freenect_camera/CMakeFiles/freenect_nodelet.dir/src/nodelets/driver.cpp.o] Error 1
make[1]: *** [freenect_stack/freenect_camera/CMakeFiles/freenect_nodelet.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/apps/haardispada_nodelet.cpp.o] Error 1
make[1]: *** [open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
thanks

**Comment by shakevincent** [comment]
@mmunaro @nanodust thank you very much!

**Comment by nanodust** [comment]
first impulse is that you should delete everything, start from scratch,
follow instructions more carefully.

the fact that

ibfreenect/libfreenect_registration.h:

is missing, indicates to me that a step was missed.
