### ISSUE TITLE
Kinect v2 test error

### ISSUE THREAD

**Issue by petersmth** [OpenPTrack/open_ptrack#105]
When I run the Test Point Cloud command for kinect v2, "roslaunch kinect2_bridge kinect2_bridge.launch", I get this error/output:

process[kinect2_head_kinect2_bridge-2]: started with pid [3018]
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenCLDepthPacketProcessor::listDevice]  devices:
  0: GeForce 940M (GPU)[NVIDIA Corporation]
[OpenCLDepthPacketProcessor::init]  selected device: GeForce 940M (GPU)[NVIDIA Corporation]
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 8 usb devices connected
[Freenect2Impl] found valid Kinect v2 @2:3 with serial 005500443447
[Freenect2Impl] found 1 devices
Kinect2 devices found: 
  0: 005500443447 (selected)
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened

starting kinect2

[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    ............C..A
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x0020:  0a 21 33 55 c2 00 17 20 00 08 00 00 10 00 00 00    .!3U... ........
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    ................
0x0040:  31 33 00 00 00 03 12 0b 47 4d 41 39 39 33 2e 31    13......GMA993.1
0x0050:  58 00 00 00 00 00 00 00 00 00 00 00                X...........

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  23 26 00 00                                        #&..

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  23 26 00 00                                        #&..

[Freenect2DeviceImpl] enabling usb transfer submission...
[Freenect2DeviceImpl] submitting usb transfers...
[Freenect2DeviceImpl] started

device serial: 005500443447
device firmware: 1.1.3323.0.7

default ir camera parameters: 
fx 364.62, fy 364.62, cx 261.888, cy 205.417
k1 0.0932319, k2 -0.271664, p1 0, p2 0, k3 0.092094

default color camera parameters: 
fx 1081.37, fy 1081.37, cx 959.5, cy 539.5

could not load calibration data from "/home/pc7/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/data/005500443447". using sensor defaults.

camera parameters used:
camera matrix color:
[1081.3720703125, 0, 959.5;
  0, 1081.3720703125, 539.5;
  0, 0, 1]
distortion coefficients color:
[0, 0, 0, 0, 0]
camera matrix ir:
[364.6199035644531, 0, 261.8876037597656;
  0, 364.6199035644531, 205.4170989990234;
  0, 0, 1]
distortion coefficients ir:
[0.09323190897703171, -0.2716636061668396, 0, 0, 0.09209399670362473]
rotation:
[1, 0, 0;
  0, 1, 0;
  0, 0, 1]
translation:
[0; 0; 0]

[DepthPacketStreamParser::handleNewData] not all subsequences received 0
[OpenCLDepthPacketProcessor::init] ERROR: clBuildProgram(-11)
[OpenCLDepthPacketProcessor::init] Build Status: -1
[OpenCLDepthPacketProcessor::init] Build Options:	
[OpenCLDepthPacketProcessor::init] Build Log:	 
terminate called after throwing an instance of 'cl::Error'
  what():  clBuildProgram
[kinect2_head_kinect2_bridge-2] process has died [pid 3018, exit code -6, cmd /home/pc7/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge __name:=kinect2_head_kinect2_bridge __log:=/home/pc7/.ros/log/26a38cea-42ee-11e6-a52d-54ab3a2e9e9c/kinect2_head_kinect2_bridge-2.log].
log file: /home/pc7/.ros/log/26a38cea-42ee-11e6-a52d-54ab3a2e9e9c/kinect2_head_kinect2_bridge-2*.log
[kinect2_head_kinect2_bridge-2] restarting process

This continues to repeat until I stop the program.

I am using a nvidia geforce 940m graphics card with nvidia-352-dev drivers. ``

**Comment by lthursdayl** [comment]
the 940m graphics card has not been tested by us to verify that it is supported per our [deployment guide](https://github.com/OpenPTrack/open_ptrack/wiki/Tested-Hardware). With that said what nvivida driver version did you install?

**Comment by lthursdayl** [comment]
also, this may solve your error:

delete the open_ptrack folder in /home/[replace with home folder]
 
Now in the terminal:
 
ln –s /home/[replace with home folder]/workspace/ros/catkin/src/open_ptrack  /home/[replace with home folder]
 
then:
 
roscd open_ptrack/../scripts
chmod +x kinect2_install.sh
./kinect2_install.sh


now try running `roslaunch kinect2_bridge kinect2_bridge.launch` again, after running ( this needs to be done after each restart)

 cd ~/workspace/ros/catkin/devel/lib/kinect2_bridge
 sudo ./kinect2_bridge
