### ISSUE TITLE
when I run this statement-“./ros_configure.sh”，Appearing the following error:

### ISSUE THREAD

**Issue by muwangchuzhong** [OpenPTrack/open_ptrack#106]
when I run this statement-“./ros_configure.sh”，Appearing the following error:

deeplearning@dl:~/open_ptrack/scripts$ ./ros_configure.sh
Base path: /home/deeplearning/workspace/ros/catkin
Source space: /home/deeplearning/workspace/ros/catkin/src
Build space: /home/deeplearning/workspace/ros/catkin/build
Devel space: /home/deeplearning/workspace/ros/catkin/devel
Install space: /home/deeplearning/workspace/ros/catkin/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/deeplearning/workspace/ros/catkin/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/deeplearning/workspace/ros/catkin/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- BUILD_SHARED_LIBS is on
WARNING: package "swissranger_camera" should not depend on metapackage "ros" but on its packages instead
WARNING: package "swissranger_camera" should not depend on metapackage "image_common" but on its packages instead
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 15 packages in topological order:
-- ~~  - calibration_toolkit (metapackage)
-- ~~  - freenect_launch
-- ~~  - freenect_stack
-- ~~  - open_ptrack (metapackage)
-- ~~  - calibration_msgs
-- ~~  - bayes
-- ~~  - opt_msgs
-- ~~  - opt_utils
-- ~~  - freenect_camera
-- ~~  - calibration_common
-- ~~  - kinect
-- ~~  - detection
-- ~~  - swissranger_camera
-- ~~  - opt_calibration
-- ~~  - tracking
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'calibration_toolkit'
-- ==> add_subdirectory(calibration_toolkit/calibration_toolkit)
-- +++ processing catkin package: 'freenect_launch'
-- ==> add_subdirectory(freenect_stack/freenect_launch)
-- +++ processing catkin package: 'freenect_stack' 
-- ==> add_subdirectory(freenect_stack/freenect_stack)
-- +++ processing catkin metapackage: 'open_ptrack'
-- ==> add_subdirectory(open_ptrack/open_ptrack)
-- +++ processing catkin package: 'calibration_msgs'
-- ==> add_subdirectory(calibration_toolkit/calibration_msgs)
-- Using these message generators: gencpp;genlisp;genpy
-- calibration_msgs: 3 messages, 1 services
-- +++ processing catkin package: 'bayes'
-- ==> add_subdirectory(open_ptrack/bayes)
-- +++ processing catkin package: 'opt_msgs'
-- ==> add_subdirectory(open_ptrack/opt_msgs)
-- Using these message generators: gencpp;genlisp;genpy
-- opt_msgs: 12 messages, 2 services
-- +++ processing catkin package: 'opt_utils'
-- ==> add_subdirectory(open_ptrack/opt_utils)
-- Eigen found (include: /usr/include/eigen3)
-- +++ processing catkin package: 'freenect_camera'
-- ==> add_subdirectory(freenect_stack/freenect_camera)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
-- +++ processing catkin package: 'calibration_common'
-- ==> add_subdirectory(calibration_toolkit/calibration_common)
-- Using these message generators: gencpp;genlisp;genpy
-- Boost version: 1.54.0
-- Eigen found (include: /usr/include/eigen3)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
-- Found required Ceres dependency: Eigen version 3.2.0 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/local/include
-- Found Ceres version: 1.9.0 installed in: /usr/local
-- +++ processing catkin package: 'kinect'
-- ==> add_subdirectory(calibration_toolkit/kinect)
-- Using these message generators: gencpp;genlisp;genpy
-- Boost version: 1.54.0
-- Eigen found (include: /usr/include/eigen3)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
-- Found required Ceres dependency: Eigen version 3.2.0 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/local/include
-- Found Ceres version: 1.9.0 installed in: /usr/local
-- +++ processing catkin package: 'detection'
-- ==> add_subdirectory(open_ptrack/detection)
-- Using these message generators: gencpp;genlisp;genpy
-- Eigen found (include: /usr/include/eigen3)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
PCL_INCLUDE_DIRS
/usr/include/pcl-1.7;/usr/include/eigen3;/usr/include;/usr/include/ni;/usr/include/vtk-5.8

PCL_LIBRARY_DIRS
/usr/lib

PCL_DEFINITIONS
-DEIGEN_USE_NEW_STDVECTOR;-DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET;-DFLANN_STATIC;-Dqh_QHpointer

PCL_COMMON_LIBRARIES
/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libpthread.so;optimized;/usr/lib/libpcl_common.so;debug;/usr/lib/libpcl_common.so

-- +++ processing catkin package: 'swissranger_camera'
-- ==> add_subdirectory(open_ptrack/swissranger_camera)
-- Using these message generators: gencpp;genlisp;genpy
-- Eigen found (include: /usr/include/eigen3)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
PCL_INCLUDE_DIRS
/usr/include/pcl-1.7;/usr/include/eigen3;/usr/include;/usr/include/ni;/usr/include/vtk-5.8

PCL_LIBRARY_DIRS
/usr/lib

PCL_DEFINITIONS
-DEIGEN_USE_NEW_STDVECTOR;-DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET;-DFLANN_STATIC;-Dqh_QHpointer

PCL_COMMON_LIBRARIES
/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_iostreams.so;/usr/lib/x86_64-linux-gnu/libboost_serialization.so;/usr/lib/x86_64-linux-gnu/libpthread.so;optimized;/usr/lib/libpcl_common.so;debug;/usr/lib/libpcl_common.so

-- +++ processing catkin package: 'opt_calibration'
-- ==> add_subdirectory(open_ptrack/opt_calibration)
-- Using these message generators: gencpp;genlisp;genpy
-- Boost version: 1.54.0
-- Eigen found (include: /usr/include/eigen3)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
OpenMP FOUND
-- +++ processing catkin package: 'tracking'
-- ==> add_subdirectory(open_ptrack/tracking)
-- Using these message generators: gencpp;genlisp;genpy
-- Eigen found (include: /usr/include/eigen3)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/deeplearning/workspace/ros/catkin/build
####
####
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] [  0%] Built target std_msgs_generate_messages_lisp
Built target std_msgs_generate_messages_py
[  9%] Built target bayes
[  9%] Built target geometry_msgs_generate_messages_py
[  9%] [  9%] [  9%] Built target _calibration_msgs_generate_messages_check_deps_CheckerboardArray
Built target _calibration_msgs_generate_messages_check_deps_CheckerboardMsg
Built target sensor_msgs_generate_messages_py
[  9%] Built target _calibration_msgs_generate_messages_check_deps_OmnicameraInfo
[  9%] Built target _calibration_msgs_generate_messages_check_deps_SetOmnicameraInfo
[  9%] Built target _opt_msgs_generate_messages_check_deps_TrackArray
[  9%] Built target _opt_msgs_generate_messages_check_deps_HumanEntries
[  9%] Built target _opt_msgs_generate_messages_check_deps_DetectionArray
[  9%] [  9%] [  9%] [  9%] Built target _opt_msgs_generate_messages_check_deps_CalibrationStatus
Built target _opt_msgs_generate_messages_check_deps_Detection
Built target _opt_msgs_generate_messages_check_deps_BoundingBox2D
Built target _opt_msgs_generate_messages_check_deps_RoiRect
[  9%] Built target geometry_msgs_generate_messages_cpp
[  9%] Built target _opt_msgs_generate_messages_check_deps_OPTTransform
[  9%] Built target _opt_msgs_generate_messages_check_deps_Rois
[  9%] Built target sensor_msgs_generate_messages_cpp
[  9%] [  9%] Built target sensor_msgs_generate_messages_lisp
[  9%] [  9%] Built target _opt_msgs_generate_messages_check_deps_HumanEntry
Built target _opt_msgs_generate_messages_check_deps_Track
Built target geometry_msgs_generate_messages_lisp
[  9%] [  9%] Built target _opt_msgs_generate_messages_check_deps_OPTSensor
Built target _opt_msgs_generate_messages_check_deps_BoundingBox3D
[ 10%] Built target roi_msgs
[ 11%] [ 11%] [ 12%] [ 15%] Built target freenect_camera_gencfg
Built target json
Built target _opt_msgs_generate_messages_check_deps_IDArray
Built target udp_listener
[ 15%] Built target opt_utils
[ 16%] [ 18%] Generating dynamic reconfigure files from cfg/SwissRanger.cfg: /home/deeplearning/workspace/ros/catkin/devel/include/swissranger_camera/SwissRangerConfig.h /home/deeplearning/workspace/ros/catkin/devel/lib/python2.7/dist-packages/swissranger_camera/cfg/SwissRangerConfig.py
Built target tracking_gencfg
[ 19%] Built target detection_gencfg
[ 22%] [ 27%] Built target calibration_algorithms
Built target calibration_msgs_generate_messages_py
[ 29%] [ 32%] Built target swissranger_utility
Built target calibration_msgs_generate_messages_cpp
[ 36%] Built target calibration_common
[ 39%] [ 51%] [ 65%] [ 77%] Built target opt_msgs_generate_messages_cpp
Built target opt_msgs_generate_messages_py
Built target calibration_msgs_generate_messages_lisp
Built target opt_msgs_generate_messages_lisp
[ 78%] Built target ros2udp_converter
[ 78%] [ 79%] [ 79%] Building CXX object freenect_stack/freenect_camera/CMakeFiles/freenect_nodelet.dir/src/nodelets/driver.cpp.o
Built target calibration_msgs_generate_messages
Built target roi_viewer
[ 80%] [ 80%] [ 80%] Built target freenect_node
[ 81%] Built target opt_msgs_generate_messages
[ 83%] Built target detection
Building CXX object open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/apps/haardispada_nodelet.cpp.o
Building CXX object open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/src/haardispada.cpp.o
[ 84%] [ 86%] Built target ground_based_people_detector
Built target ground_based_people_detector_sr
[ 87%] Built target opt_calibration_refinement
[ 88%] Built target stereo_publisher
[ 91%] Built target opt_calibration
[ 94%] Built target tracking
[ 97%] Built target opt_define_reference_frame
[ 98%] Built target moving_average_filter
[ 98%] Built target tracker
Generating reconfiguration files for SwissRanger in swissranger_camera
[ 98%] Built target swissranger_camera_gencfg
In file included from /home/deeplearning/workspace/ros/catkin/src/freenect_stack/freenect_camera/include/freenect_camera/freenect_driver.hpp:5:0,
                 from /home/deeplearning/workspace/ros/catkin/src/freenect_stack/freenect_camera/src/nodelets/driver.h:54,
                 from /home/deeplearning/workspace/ros/catkin/src/freenect_stack/freenect_camera/src/nodelets/driver.cpp:39:
/home/deeplearning/workspace/ros/catkin/src/freenect_stack/freenect_camera/include/freenect_camera/freenect_device.hpp:11:50: fatal error: libfreenect/libfreenect_registration.h: No such file or directory
compilation terminated.
In file included from /home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:31:0:
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/include/open_ptrack/detection/haardispada.h:63:16: error: 'cv::INTER_AREA' has not been declared
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/include/open_ptrack/detection/haardispada.h:104:9: error: 'CvBoost' does not name a type
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'void open_ptrack::detection::HaarDispAdaClassifier::detect(std::vector<cv::Rect_<int> >&, std::vector<int>&, cv::Mat&, std::vector<cv::Rect_<int> >&, std::vector<int>&, bool)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:83:22: error: 'HDAC_' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'void open_ptrack::detection::HaarDispAdaClassifier::detect(std::vector<cv::Rect_<int> >&, std::vector<int>&, cv::Mat&, std::vector<cv::Rect_<int> >&, std::vector<int>&, std::vector<float>&, bool)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:123:22: error: 'HDAC_' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'void open_ptrack::detection::HaarDispAdaClassifier::train(std::string)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:191:7: error: 'CvBoostParams' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:191:21: error: expected ';' before 'bparams'
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:193:7: error: 'bparams' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:212:44: error: 'CV_VAR_ORDERED' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:214:7: error: 'HDAC_' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:214:29: error: 'CV_ROW_SAMPLE' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'void open_ptrack::detection::HaarDispAdaClassifier::load(std::string)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:283:7: error: 'HDAC_' was not declared in this scope
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'int open_ptrack::detection::HaarDispAdaClassifier::haar_features_fast(cv::Mat&)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:415:7: error: 'resize' is not a member of 'cv'
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:416:7: error: 'resize' is not a member of 'cv'
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp: In member function 'int open_ptrack::detection::HaarDispAdaClassifier::haar_features(cv::Mat&, cv::Mat&)':
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/src/haardispada.cpp:470:90: error: 'resize' was not declared in this scope
make[2]: *** [open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/src/haardispada.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/apps/haardispada_nodelet.cpp:40:0:
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/include/open_ptrack/detection/haardispada.h:63:16: error: 'cv::INTER_AREA' has not been declared
/home/deeplearning/workspace/ros/catkin/src/open_ptrack/detection/include/open_ptrack/detection/haardispada.h:104:9: error: 'CvBoost' does not name a type
make[2]: *** [freenect_stack/freenect_camera/CMakeFiles/freenect_nodelet.dir/src/nodelets/driver.cpp.o] Error 1
make[1]: *** [freenect_stack/freenect_camera/CMakeFiles/freenect_nodelet.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/apps/haardispada_nodelet.cpp.o] Error 1
make[1]: *** [open_ptrack/detection/CMakeFiles/haar_disp_ada.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
Error: There already is a workspace config file .rosinstall at "/home/deeplearning/workspace/ros/rosbuild". Use rosws install/modify.

**Comment by nanodust** [comment]
this log is very system specific, hard to debug. Please verify you're running on supported hardware, and following installation instructions explicitly. If you still have errors, please make a new issue.
