### ISSUE TITLE
when I run this statement-“./openptrack_install.sh”，Appearing the following error: 

### ISSUE THREAD

**Issue by muwangchuzhong** [OpenPTrack/open_ptrack#107]
when I run this statement-“./openptrack_install.sh”，Appearing the following error: 

dpkg: error processing archive libmesasr-dev-1.0.14-748.amd64.deb (--install):
 无法访问归档文件: 没有那个文件或目录
在处理时有错误发生：
 libmesasr-dev-1.0.14-748.amd64.deb
Base path: /home/lyz/workspace/ros/catkin
Source space: /home/lyz/workspace/ros/catkin/src
Build space: /home/lyz/workspace/ros/catkin/build
Devel space: /home/lyz/workspace/ros/catkin/devel
Install space: /home/lyz/workspace/ros/catkin/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/lyz/workspace/ros/catkin/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/lyz/workspace/ros/catkin/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- BUILD_SHARED_LIBS is on
WARNING: package "swissranger_camera" should not depend on metapackage "ros" but on its packages instead
WARNING: package "swissranger_camera" should not depend on metapackage "image_common" but on its packages instead
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 15 packages in topological order:
-- ~~  - calibration_toolkit (metapackage)
-- ~~  - freenect_launch
-- ~~  - freenect_stack
-- ~~  - open_ptrack (metapackage)
-- ~~  - calibration_msgs
-- ~~  - bayes
-- ~~  - opt_msgs
-- ~~  - opt_utils
-- ~~  - freenect_camera
-- ~~  - calibration_common
-- ~~  - kinect
-- ~~  - detection
-- ~~  - swissranger_camera
-- ~~  - opt_calibration
-- ~~  - tracking
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'calibration_toolkit'
-- ==> add_subdirectory(calibration_toolkit/calibration_toolkit)
-- +++ processing catkin package: 'freenect_launch'
-- ==> add_subdirectory(freenect_stack/freenect_launch)
-- +++ processing catkin package: 'freenect_stack'
-- ==> add_subdirectory(freenect_stack/freenect_stack)
-- +++ processing catkin metapackage: 'open_ptrack'
-- ==> add_subdirectory(open_ptrack/open_ptrack)
-- +++ processing catkin package: 'calibration_msgs'
-- ==> add_subdirectory(calibration_toolkit/calibration_msgs)
-- Using these message generators: gencpp;genlisp;genpy
-- calibration_msgs: 3 messages, 1 services
-- +++ processing catkin package: 'bayes'
-- ==> add_subdirectory(open_ptrack/bayes)
-- +++ processing catkin package: 'opt_msgs'
-- ==> add_subdirectory(open_ptrack/opt_msgs)
-- Using these message generators: gencpp;genlisp;genpy
-- opt_msgs: 12 messages, 2 services
-- +++ processing catkin package: 'opt_utils'
-- ==> add_subdirectory(open_ptrack/opt_utils)
-- Eigen found (include: /usr/include/eigen3)
-- +++ processing catkin package: 'freenect_camera'
-- ==> add_subdirectory(freenect_stack/freenect_camera)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
-- +++ processing catkin package: 'calibration_common'
-- ==> add_subdirectory(calibration_toolkit/calibration_common)
-- Using these message generators: gencpp;genlisp;genpy
-- Boost version: 1.54.0
-- Eigen found (include: /usr/include/eigen3)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
CMake Error at calibration_toolkit/calibration_common/CMakeLists.txt:23 (FIND_PACKAGE):
  By not providing "FindCeres.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Ceres", but
  CMake did not find one.

  Could not find a package configuration file provided by "Ceres" with any of
  the following names:

    CeresConfig.cmake
    ceres-config.cmake

  Add the installation prefix of "Ceres" to CMAKE_PREFIX_PATH or set
  "Ceres_DIR" to a directory containing one of the above files.  If "Ceres"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/lyz/workspace/ros/catkin/build/CMakeFiles/CMakeOutput.log".
See also "/home/lyz/workspace/ros/catkin/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] 错误 1
Invoking "make cmake_check_build_system" failed
Base path: /home/lyz/workspace/ros/catkin
Source space: /home/lyz/workspace/ros/catkin/src
Build space: /home/lyz/workspace/ros/catkin/build
Devel space: /home/lyz/workspace/ros/catkin/devel
Install space: /home/lyz/workspace/ros/catkin/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/lyz/workspace/ros/catkin/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/lyz/workspace/ros/catkin/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- BUILD_SHARED_LIBS is on
WARNING: package "swissranger_camera" should not depend on metapackage "ros" but on its packages instead
WARNING: package "swissranger_camera" should not depend on metapackage "image_common" but on its packages instead
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 15 packages in topological order:
-- ~~  - calibration_toolkit (metapackage)
-- ~~  - freenect_launch
-- ~~  - freenect_stack
-- ~~  - open_ptrack (metapackage)
-- ~~  - calibration_msgs
-- ~~  - bayes
-- ~~  - opt_msgs
-- ~~  - opt_utils
-- ~~  - freenect_camera
-- ~~  - calibration_common
-- ~~  - kinect
-- ~~  - detection
-- ~~  - swissranger_camera
-- ~~  - opt_calibration
-- ~~  - tracking
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'calibration_toolkit'
-- ==> add_subdirectory(calibration_toolkit/calibration_toolkit)
-- +++ processing catkin package: 'freenect_launch'
-- ==> add_subdirectory(freenect_stack/freenect_launch)
-- +++ processing catkin package: 'freenect_stack'
-- ==> add_subdirectory(freenect_stack/freenect_stack)
-- +++ processing catkin metapackage: 'open_ptrack'
-- ==> add_subdirectory(open_ptrack/open_ptrack)
-- +++ processing catkin package: 'calibration_msgs'
-- ==> add_subdirectory(calibration_toolkit/calibration_msgs)
-- Using these message generators: gencpp;genlisp;genpy
-- calibration_msgs: 3 messages, 1 services
-- +++ processing catkin package: 'bayes'
-- ==> add_subdirectory(open_ptrack/bayes)
-- +++ processing catkin package: 'opt_msgs'
-- ==> add_subdirectory(open_ptrack/opt_msgs)
-- Using these message generators: gencpp;genlisp;genpy
-- opt_msgs: 12 messages, 2 services
-- +++ processing catkin package: 'opt_utils'
-- ==> add_subdirectory(open_ptrack/opt_utils)
-- Eigen found (include: /usr/include/eigen3)
-- +++ processing catkin package: 'freenect_camera'
-- ==> add_subdirectory(freenect_stack/freenect_camera)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
-- +++ processing catkin package: 'calibration_common'
-- ==> add_subdirectory(calibration_toolkit/calibration_common)
-- Using these message generators: gencpp;genlisp;genpy
-- Boost version: 1.54.0
-- Eigen found (include: /usr/include/eigen3)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
CMake Error at calibration_toolkit/calibration_common/CMakeLists.txt:23 (FIND_PACKAGE):
  By not providing "FindCeres.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Ceres", but
  CMake did not find one.

  Could not find a package configuration file provided by "Ceres" with any of
  the following names:

    CeresConfig.cmake
    ceres-config.cmake

  Add the installation prefix of "Ceres" to CMAKE_PREFIX_PATH or set
  "Ceres_DIR" to a directory containing one of the above files.  If "Ceres"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/lyz/workspace/ros/catkin/build/CMakeFiles/CMakeOutput.log".
See also "/home/lyz/workspace/ros/catkin/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] 错误 1
Invoking "make cmake_check_build_system" failed
Base path: /home/lyz/workspace/ros/catkin
Source space: /home/lyz/workspace/ros/catkin/src
Build space: /home/lyz/workspace/ros/catkin/build
Devel space: /home/lyz/workspace/ros/catkin/devel
Install space: /home/lyz/workspace/ros/catkin/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/lyz/workspace/ros/catkin/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/lyz/workspace/ros/catkin/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- BUILD_SHARED_LIBS is on
WARNING: package "swissranger_camera" should not depend on metapackage "ros" but on its packages instead
WARNING: package "swissranger_camera" should not depend on metapackage "image_common" but on its packages instead
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 15 packages in topological order:
-- ~~  - calibration_toolkit (metapackage)
-- ~~  - freenect_launch
-- ~~  - freenect_stack
-- ~~  - open_ptrack (metapackage)
-- ~~  - calibration_msgs
-- ~~  - bayes
-- ~~  - opt_msgs
-- ~~  - opt_utils
-- ~~  - freenect_camera
-- ~~  - calibration_common
-- ~~  - kinect
-- ~~  - detection
-- ~~  - swissranger_camera
-- ~~  - opt_calibration
-- ~~  - tracking
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin metapackage: 'calibration_toolkit'
-- ==> add_subdirectory(calibration_toolkit/calibration_toolkit)
-- +++ processing catkin package: 'freenect_launch'
-- ==> add_subdirectory(freenect_stack/freenect_launch)
-- +++ processing catkin package: 'freenect_stack'
-- ==> add_subdirectory(freenect_stack/freenect_stack)
-- +++ processing catkin metapackage: 'open_ptrack'
-- ==> add_subdirectory(open_ptrack/open_ptrack)
-- +++ processing catkin package: 'calibration_msgs'
-- ==> add_subdirectory(calibration_toolkit/calibration_msgs)
-- Using these message generators: gencpp;genlisp;genpy
-- calibration_msgs: 3 messages, 1 services
-- +++ processing catkin package: 'bayes'
-- ==> add_subdirectory(open_ptrack/bayes)
-- +++ processing catkin package: 'opt_msgs'
-- ==> add_subdirectory(open_ptrack/opt_msgs)
-- Using these message generators: gencpp;genlisp;genpy
-- opt_msgs: 12 messages, 2 services
-- +++ processing catkin package: 'opt_utils'
-- ==> add_subdirectory(open_ptrack/opt_utils)
-- Eigen found (include: /usr/include/eigen3)
-- +++ processing catkin package: 'freenect_camera'
-- ==> add_subdirectory(freenect_stack/freenect_camera)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   thread
-- +++ processing catkin package: 'calibration_common'
-- ==> add_subdirectory(calibration_toolkit/calibration_common)
-- Using these message generators: gencpp;genlisp;genpy
-- Boost version: 1.54.0
-- Eigen found (include: /usr/include/eigen3)
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
--   date_time
--   iostreams
--   serialization
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
CMake Error at calibration_toolkit/calibration_common/CMakeLists.txt:23 (FIND_PACKAGE):
  By not providing "FindCeres.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Ceres", but
  CMake did not find one.

  Could not find a package configuration file provided by "Ceres" with any of
  the following names:

    CeresConfig.cmake
    ceres-config.cmake

  Add the installation prefix of "Ceres" to CMAKE_PREFIX_PATH or set
  "Ceres_DIR" to a directory containing one of the above files.  If "Ceres"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/lyz/workspace/ros/catkin/build/CMakeFiles/CMakeOutput.log".
See also "/home/lyz/workspace/ros/catkin/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by itsZheng** [comment]
follow this site to install Ceres
http://ceres-solver.org/building.html

 run this statement-“./openptrack_install.sh” again

**Comment by muwangchuzhong** [comment]
@itsZheng Thanks a lot! I solve this problem.

**Comment by muwangchuzhong** [comment]
but I have a new problem,when I run "./kinect2_install.sh",Appearing the following error: 
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp: In constructor 'Kinect2Bridge::Kinect2Bridge(std::string, double, bool, int, int)':
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:60:15: warning: 'Kinect2Bridge::cameraName' will be initialized after [-Wreorder]
   std::string cameraName;
               ^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:52:17: warning:   'const int32_t Kinect2Bridge::jpegQuality' [-Wreorder]
   const int32_t jpegQuality;
                 ^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:135:3: warning:   when initialized here [-Wreorder]
   Kinect2Bridge(std::string cameraName, const double fps, const bool rawDepth, const int compression, const int deviceIdDepth)
   ^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp: In member function 'bool Kinect2Bridge::init(const string&, const string&, int, float, float)':
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:208:5: error: incomplete type 'libfreenect2::DepthPacketProcessor' used in nested name specifier
     libfreenect2::DepthPacketProcessor::Config config;
     ^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:208:48: error: expected ';' before 'config'
     libfreenect2::DepthPacketProcessor::Config config;
                                                ^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:209:5: error: 'config' was not declared in this scope
     config.MinDepth = min_depth;
     ^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:211:46: error: invalid use of incomplete type 'class libfreenect2::DepthPacketProcessor'
     packetPipeline->getDepthPacketProcessor()->setConfiguration(config);
                                              ^
In file included from /usr/local/include/libfreenect2/libfreenect2.hpp:34:0,
                 from /home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:41:
/usr/local/include/libfreenect2/packet_pipeline.h:41:7: error: forward declaration of 'class libfreenect2::DepthPacketProcessor'
 class DepthPacketProcessor;
       ^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp: In member function 'void Kinect2Bridge::equalizeImage(cv::Mat&, cv::Mat&)':
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:609:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (unsigned int i = 0; i < input_image.rows; i++)
                                              ^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:611:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (unsigned int j = 0; j < input_image.cols; j++)
                                                ^
make[2]: *** [iai_kinect2/kinect2_bridge/CMakeFiles/kinect2_bridge.dir/src/kinect2_bridge.cpp.o] Error 1
make[1]: *** [iai_kinect2/kinect2_bridge/CMakeFiles/kinect2_bridge.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by itsZheng** [comment]
#56 
Kinect v2 Install Error #56

Good luck！

**Comment by smarthhy** [comment]
HI

Have you solved the problem?what should I do? thanks

/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:208:48: error: expected ';' before 'config'
libfreenect2::DepthPacketProcessor::Config config;
^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:209:5: error: 'config' was not declared in this scope
config.MinDepth = min_depth;
^
/home/lyz/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/src/kinect2_bridge.cpp:211:46: error: invalid use of incomplete type 'class libfreenect2::DepthPacketProcessor'
packetPipeline->getDepthPacketProcessor()->setConfiguration(config);
^
