### ISSUE TITLE
when I run "roslaunch tracking detection_and_tracking_kinect2.launch"to test Single-Camera Tracking ,it can work，but it didn‘t work properly，

### ISSUE THREAD

**Issue by muwangchuzhong** [OpenPTrack/open_ptrack#110]
when I run "roslaunch tracking detection_and_tracking_kinect2.launch"to test Single-Camera Tracking ,it can work，but it didn‘t work properly，such as
![3](https://cloud.githubusercontent.com/assets/20319194/17013918/fb9bbd34-4f53-11e6-8371-dfad6de7c634.png)

Why it does not work properly??
Thanks everybody.
@itsZheng
@nanodust 
@mmunaro

**Comment by muwangchuzhong** [comment]
and it cannot detect people even though people appear in front of the camera。

**Comment by mmunaro** [comment]
For that single-camera launch file, the ground plane is automatically estimated.
However, in your scenario, the ground plane is hardly visible, thus it has been badly estimated (this is clear from the position of the detections).
Try to have more ground in the field of view of the camera.

**Comment by muwangchuzhong** [comment]
Thank  you @mmunaro ,According to what you said,I  solve the above problems,but I have a new problem: Program can detect and track people,and it has accurate location in PCL,such as
![pcl](https://cloud.githubusercontent.com/assets/20319194/17045587/3b91be08-4ffd-11e6-9571-57f6e29de12d.png)
but Program can detect and track people,it does not have accurate location in RGB window,detection rectangular frame cannot correspond with people.such as
![rgb](https://cloud.githubusercontent.com/assets/20319194/17045722/a6cfc790-4ffe-11e6-9b7d-be0e470f5985.png)
Why?

**Comment by muwangchuzhong** [comment]
I have found that this problem is due to difference between Color Camera  resolution and Depth Sensor  resolution，but I want it can work well in the RGB window，who can help me？Thanks

**Comment by jburkeucla** [comment]
Abandoned issue? Closing.
