### ISSUE TITLE
Memory Leak on Master & Dev Branch

### ISSUE THREAD

**Issue by lthursdayl** [OpenPTrack/open_ptrack#114]
We have discovered a memory leak on the development branch. With each new person that enters the space a few MBs (between 3 - 4 MBs) are added to the tracker process’s RAM usage. The available RAM is being consumed by the tracker until the computer crashes. The system that the memory leak was discovered on is needing restarting everyday due to the RAM being consumed (the computer the tracker is run on has 8GB of RAM).

This installation is using the newest version of the development branch, and is using (5) Kinect 2 and (6) computers. The sixth computer acts as the master.

**Comment by jburkeucla** [comment]
Randy, when you can, please verify this on another system with 1) dev branch and 2) master branch.   My guess is this is due to not reclaiming memory when people exit and are no longer tracked.

**Comment by lthursdayl** [comment]
Attached are screenshots that show the RAM consumption. 
![screenshot from 2016-08-16 19_39_38](https://cloud.githubusercontent.com/assets/4822247/17743122/82b49b20-6457-11e6-9090-041076696106.png)
![screenshot from 2016-08-16 18_18_48](https://cloud.githubusercontent.com/assets/4822247/17743123/82b4f8d6-6457-11e6-90fd-bb6f010d64c9.png)
![screenshot from 2016-08-16 19_21_06](https://cloud.githubusercontent.com/assets/4822247/17743124/82b51596-6457-11e6-8de6-c4f2c93beeb4.png)
![screenshot from 2016-08-16 19_39_16](https://cloud.githubusercontent.com/assets/4822247/17743121/82b42280-6457-11e6-9376-70c9b20b26f4.png)

**Comment by lthursdayl** [comment]
I just confirmed that the memory leak is on both the dev and master branch

**Comment by marketto89** [comment]
This has been fixed with commit [2341a51](https://github.com/OpenPTrack/open_ptrack/commit/2341a51459fb962e56d24c819c09bf2278828e50) on master branch. The same commit has been cherry-picked in development branch and jetson-dev branch.

**Comment by nanodust** [comment]
nice work !!!
