### ISSUE TITLE
Support for ZED Camera

### ISSUE THREAD

**Issue by RudyChin** [OpenPTrack/open_ptrack#116]
Hi, 
This is an excellent project! Is it possible to pre-record a RGB-D video with ZED camera and run it with OPT?
If it is possible, what kind of format should the video be to function OPT correctly?
Thanks!
Rudy

**Comment by lthursdayl** [comment]
Hi,
Regarding recording RGB-D for use with OpenPTrack, here are two starting points that may help you find the answer:

https://github.com/OpenPTrack/open_ptrack/wiki/Tips-and-Tricks#ros-tricks

and 

http://wiki.ros.org/rosbag

OpenPTrack utilizes rosbags for playback.
