### ISSUE TITLE
Build in Ubuntu 16.04 error

### ISSUE THREAD

**Issue by aaramirezd** [OpenPTrack/open_ptrack#119]
Excellent development.
I'm trying build the project in ubuntu 16.04 and kinetic ros distro. 
I have installed Kinetic previously
I installed all dependencies
This is the error:

Base path: /home/andres/catkin_ws
Source space: /home/andres/catkin_ws/src
Build space: /home/andres/catkin_ws/build
Devel space: /home/andres/catkin_ws/devel
Install space: /home/andres/catkin_ws/install
####
####
####
####
[ 50%] Built target bayes
[ 50%] Built target opt_utils
[ 62%] Built target json
[ 75%] Built target tracking_gencfg
[ 87%] Built target detection_gencfg
[ 87%] Building CXX object open_ptrack/detection/CMakeFiles/detection.dir/src/detection_source.cpp.o
[ 87%] Building CXX object open_ptrack/detection/CMakeFiles/detection.dir/src/detection.cpp.o
/bin/sh: 1: /bin/sh: 1: Syntax error: "(" unexpected
Syntax error: "(" unexpected
open_ptrack/detection/CMakeFiles/detection.dir/build.make:62: recipe for target 'open_ptrack/detection/CMakeFiles/detection.dir/src/detection_source.cpp.o' failed
make[2]: *** [open_ptrack/detection/CMakeFiles/detection.dir/src/detection_source.cpp.o] Error 2
make[2]: *** Waiting for unfinished jobs....
open_ptrack/detection/CMakeFiles/detection.dir/build.make:86: recipe for target 'open_ptrack/detection/CMakeFiles/detection.dir/src/detection.cpp.o' failed
make[2]: *** [open_ptrack/detection/CMakeFiles/detection.dir/src/detection.cpp.o] Error 2
CMakeFiles/Makefile2:10438: recipe for target 'open_ptrack/detection/CMakeFiles/detection.dir/all' failed
make[1]: *** [open_ptrack/detection/CMakeFiles/detection.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

any ideas?
Andrés

**Comment by nanodust** [comment]
quick scan here -

a) openptrack is supported for 14.04 LTS - not 16.04 It might work in 16.04
but don't expect much help here until. stick with 14.04 until you know the
system well.

b) paths are suspect - ../catkin_ws/build/open_ptrack/tracking is not a
path i've ever had during installation.

I'd suggest wiping this, starting over with 14.04 LTS, and make sure to
follow precisely the suggested / example paths.

**Comment by nanodust** [comment]
a) openptrack is supported for 14.04 LTS - not 16.04. per guide @ https://github.com/OpenPtrack/open_ptrack/wiki/Supported-Hardware

It might work in 16.04 but don't expect much help here until. 
stick with 14.04 until you know the system well. 

b) paths are suspect - ../catkin_ws/build/open_ptrack/tracking is not a path i've ever had during installation. 

I'd suggest wiping this, starting over with 14.04 LTS, and make sure to follow precisely the suggested / example paths.

**Comment by aaramirezd** [comment]
Alex Nano:
Thanks for your quick reply,  I will install on ubuntu 14.04.

However, i'm interested in doing the update and can try, in his research group someone would be interested in doing?

Andrés

**Comment by jburkeucla** [comment]
We'd be happy to know what's necessary to get it running on Ubuntu 16.04, just don't have cycles to help with it right now.
