### ISSUE TITLE
kinect2_bridge_ir.launch, no such file or directory

### ISSUE THREAD

**Issue by aaramirezd** [OpenPTrack/open_ptrack#120]
Hi:

When I try  "roslaunch tracking detection_and_tracking_kinect2.launch" the following error occurs

while processing /home/andres/workspace/ros/catkin/src/open_ptrack/detection/launch/detector_depth_kinect2.launch:
while processing /home/andres/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/launch/kinect2_bridge_ir.launch:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/home/andres/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/launch/kinect2_bridge_ir.launch'
The traceback for the exception was written to the log file

The launch file does not exist, I have to build manually?

Andrés
Thanks

**Comment by marketto89** [comment]
@aaramirezd,

Are you sure to work with the correct branch? You should be in the devel or jetson-dev branch to launch that command.

Could you confirm that you are in one of those branches?

**Comment by aaramirezd** [comment]
Hi, 

I have the master branch, but the launch file in detection package include the follow line:

 <include file="$(find kinect2_bridge)/launch/kinect2_bridge_ir.launch">

but de kinect2_bridge package does not include this file
change the launch file name?
Andrés

**Comment by nanodust** [comment]
as marketto89 indicated, you appear to be in the wrong branch.
