### ISSUE TITLE
Kinect 2 

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#121]
Hello ! It's been a while :)

I've not installed this from scratch in a while (nearly a year!) - but last few times I did, it worked just fine. 

I'm trying again - on the same hardware that it ran previously - and I get no errors during installation, until I actually run tracking. 

yes, i run 

```
worker@worker:~/workspace/ros/catkin/devel/lib/kinect2_bridge$  sudo ./kinect2_bridge
```

works fine, normal red output as noted in doc. 

yet this fails -and i'm not sure why.  Any ideas ? 

```
worker@worker:~/workspace/ros/catkin/devel/lib/kinect2_bridge$ roslaunch kinect2_bridge 

....
Kinect2 devices found: 
  0: 074493140847 (selected)
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened

starting kinect2

[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    ............C..A
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x0020:  0a 21 33 55 c2 00 17 20 00 08 00 00 10 00 00 00    .!3U... ........
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    ................
0x0040:  31 33 00 00 00 00 0e 03 47 48 56 32 32 31 2e 31    13......GHV221.1
0x0050:  58 00 00 00 00 00 00 00 00 00 00 00                X...........

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  01 26 00 00                                        .&..

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  03 26 00 00                                        .&..

[Freenect2DeviceImpl] enabling usb transfer submission...
[Freenect2DeviceImpl] submitting usb transfers...
[Freenect2DeviceImpl] started

device serial: 074493140847
device firmware: 1.1.3323.0.7

default ir camera parameters: 
fx 365.74, fy 365.74, cx 254.186, cy 202.051
k1 0.0913988, k2 -0.269299, p1 0, p2 0, k3 0.097657

default color camera parameters: 
fx 1081.37, fy 1081.37, cx 959.5, cy 539.5

could not load calibration data from "/home/worker/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/data/074493140847". using sensor defaults.

.....

[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
[DepthRegistrationOpenCL::listDevice]  devices:
  0: GeForce GTX 750 Ti (GPU)[NVIDIA Corporation]
[DepthRegistrationOpenCL::init]  selected device: GeForce GTX 750 Ti (GPU)[NVIDIA Corporation]
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
[DepthRegistrationOpenCL::listDevice]  devices:
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
  0: GeForce GTX 750 Ti (GPU)[NVIDIA Corporation]
[DepthRegistrationOpenCL::init]  selected device: GeForce GTX 750 Ti (GPU)[NVIDIA Corporation]
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
set process thread priority to: 19
set process thread priority to: 19
set process thread priority to: 19
set process thread priority to: 19
set process thread priority to: 19
set process thread priority to: 19
starting main loop
set process thread priority to: 19
set process thread priority to: 19
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
[TurboJpegRgbPacketProcessor::doProcess] Failed to decompress rgb image! TurboJPEG error: 'Invalid JPEG file structure: two SOI markers'
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
```

this last line then just keeps looping , ad infinitum.

**Comment by nanodust** [comment]
I reformatted system to 14.04. trying again. 

if this doesn't work, i'll reformat and try again from 'development' branch.

**Comment by lthursdayl** [comment]
Were you on ubuntu 16.04 previously? We have installed opt on three or four fresh machines running ubuntu 14.04 this week without issue. Let us know if you are still having trouble after the reformat.

**Comment by nanodust** [comment]
All 14.04

Same shuttles ive put it on a few times...

What are you using these days ? Master or dev ?

**Comment by lthursdayl** [comment]
Master and dev are the same at the moment. Using master, in general.

**Comment by nanodust** [comment]
indeed they are :) i tried both, i get the exact same error as before I started :)

 I know I've followed instructions correctly.

```
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
```
just loops infinitely.

I vaguely recall this error - but I don't recall the fix :)

was trying to get it back live for a demo tomorrow... will keep at it...

**Comment by nanodust** [comment]
I continued as if it there was no kinect2 driver error - there is no data for the topics (points, ir, or rgb), and

```
 rostopic hz /kinect2_head/depth_lowres/points 
```
hangs/returns nothing

Now i notice the warning 
```
This has been tested with Ubuntu kernel 3.13.0-37-generic. There were some USB3 issues with previous versions of the kernel.
```
```
uname -a
Linux worker 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
so, despite this being a completely fresh new install of ubuntu - it's  3.13.0-32 not 3.13.0-37

and... if it worked 6 mos ago, it certainly wasn't 3.13.0-37 ! 

if/when you get a chance, run uname -a on the machines you get configured ? 

i'll spend a bit more time w/ it now, but if i can't get Kinect 2 then i'll move back to Kinect 1 first thing in am.

**Comment by nanodust** [comment]
OK - pretty sure this is *not* a kernel version issue..  I tried a few different versions (recompiling freenect each time) and ended up with a few different errors, but ultimately with the latest kernel for 'trusty' - i get the exact same error as I started with. 

via [forum](http://askubuntu.com/questions/119080/how-to-update-kernel-to-the-latest-mainline-version-without-any-distro-upgrade)  :

http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.13.1-trusty/

linux-headers-3.13.1-031301-generic_3.13.1-031301.201401291035_amd64.deb
linux-headers-3.13.1-031301_3.13.1-031301.201401291035_all.deb
linux-image-3.13.1-031301-generic_3.13.1-031301.201401291035_amd64.deb

sudo dpkg -i *.deb


3.13.1-031301-generic


ok- new kernel, i suspect i'd need to re-install nvidia as well as possibly the kinect2 driver. 

first, let's test, and only do that if it fails. 
```
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 12 00 00 00 00 00 01 00 00 00 43 c1 1f 41    ............C..A
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x0020:  0a 21 33 55 c2 00 17 20 00 08 00 00 10 00 00 00    .!3U... ........
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    ................
0x0040:  31 33 00 00 00 00 0e 03 47 48 56 32 32 31 2e 31    13......GHV221.1
0x0050:  58 00 00 00 00 00 00 00 00 00 00 00                X...........

[CommandTransaction::receive] bulk transfer failed! libusb error -1: LIBUSB_ERROR_IO
*** Error in `/home/worker/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge': double free or corruption (top): 0x0000000001f5c690 ***
^C[kinect2_head_points_xyzrgb_highres-4] killing on exit
[kinect2_head_points_xyzrgb_lowres-3] killing on exit
[kinect2_head_kinect2_bridge-2] killing on exit
```

nope - fail - 

```
./kinect2_install.sh
 cd ~/workspace/ros/catkin/src`
 roscd open_ptrack/../scripts
 ./kinect2_install.sh
```

reboot...

nope

no amount of re-installing gets rid of the CommandTransaction::receive] bulk transfer failed! libusb error -1: LIBUSB_ERROR_IO


what i'm not sure of, if this is a module that needs recompiling against the new kernel, or if it's actually a problem with this verion of the kernel. 

let's just move to a radically new kernel, and try again. 

http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.14.1-trusty/

```
linux-headers-3.14.1-031401-generic_3.14.1-031401.201404141220_amd64.deb
linux-headers-3.14.1-031401_3.14.1-031401.201404141220_all.deb
linux-image-3.14.1-031401-generic_3.14.1-031401.201404141220_amd64.deb
```

ok rebooted... let's just OPT, and then recompile at least freenect if not working. 

recompiled... 

rebooted....

nope - exact same original error - seeems to initlaize ok but then loops on:
```
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!
[DepthPacketStreamParser::handleNewData] remaining data should be 8 bytes, but is 2646
```

**Comment by nanodust** [comment]
nope - i'm giving up on this. will re-install ubuntu from scratch, and set up kinect v1 in the morning.

**Comment by nanodust** [comment]
and... nope. neither openni or freenect working w/ the kinect - also the one I previously used on this hardware w/ freenect. 

out of time today, at least for this morning. There is another demo thursday, I would still like to get this working.

**Comment by nanodust** [comment]
I'm re-installing ubuntu 14.04, will try again on clean system to get Kinect 2 working.

**Comment by nanodust** [comment]
perhpas i should just try getting kinect2 working independent of OPT, see if i learn anything from that ? 
https://github.com/code-iai/iai_kinect2

**Comment by marketto89** [comment]
@nanodust 

I agree with you that your best option is to install the Kinect v2 and test it before installing OPT.

I would say it is enough to make it work using only libfreenect2 (iai_kinect2 is just a wrapper for it).

You can either use [our version of libfreenect2](https://github.com/openptrack/libfreenect2) or the [baseline version](https://github.com/openkinect/libfreenect2).

Take care that the baseline version is not compatible with OpenPTrack.

**Comment by nanodust** [comment]
finally revisiting this... I do get the same result (following instructions on supported hardware, kinect 2 just loops '[DepthPacketStreamParser::handleNewData] working buffer full, resetting it!' and I get null  rostopic hz /kinect2_head/depth_lowres/points .

so, I am trying with just your version of libfreenect2. and I get the same result, everything compiles fine, but ./bin/Protonect gives the same 'working buffer full' error. I do however this time notice a '[TurboJpegRgbPacketProcessor::doProcess] Failed to decompress rgb image! TurboJPEG error: 'Invalid JPEG file structure: two SOI markers'' error. 

yet on baseline version of libfrenect2, I have much better success - the driver is obviously streaming successfully from kinect2. I don't see any graphics on the desktop, yet there are no errors in stdout... i will reboot and try again..

**Comment by nanodust** [comment]
libfreenect2 baseline interferes w/ nvidia driver, I cannot get X11 to load after working with it. 

I was concerned I had a hardware problem - I installed Windows 10, and tested Kinect 2 SDK - everything worked as expected. The video was 28 fps vs 30 fps - so it was a tad slow - however, this is a system I previously had installed OPT& Kinect 2 on without problem in April 2015.

I'm reinstalling ubuntu 14.04 and will try again...

perhaps I will revert OPT codebase to April 2015 to check whether it's OPT code or dependency that is the block.

**Comment by nanodust** [comment]
well - that worked. 

git checkout [ddf74](https://github.com/OpenPTrack/open_ptrack/commit/ddf741c486e01067cc5f950961eabc348df4408e)... (my last commit, july 2015)

then just followed instructions...  everything is working as expected :) 

I will roll it forward and see what was root cause...

**Comment by nanodust** [comment]
indeed, it's all working perfectly ! 

something peculiar to my system here... yet repeatable... i will diff and see what could be culprit. meanwhile I will close this issue.
