### ISSUE TITLE
Ubuntu 16.04, build done

### ISSUE THREAD

**Issue by aaramirezd** [OpenPTrack/open_ptrack#122]
Hi,

I tried to update open_ptrack packages for ubuntu 16.04 and I got some partial results, but i still need some help.

I use the latest version of kinect2_bridge and libfreenect and other changes for use opencv 3 (ROS->Kinetic), cuda.

I have a doubt regarding the branch and correct file combination. I am sure that I downloaded the master branch but this already incorporated into "detection_kinect2.launch", the line "kinect2_bridge_ir.launch". I changed this line for "kinect2_bridge.launch" and also changed the "pointcloud_topic" for the point topic into the new kinect2_bridge version.

Everything seems to work fine, but when I execute detection, the person's marker always appears very close to the frame of the camera that is following it

My questions is this: What is the correct combination of files and topics for detection? this in order to adjust my code correctly.

Example:

detection with rgb:
- kinect2_bridge.launch
- ground_based_people_detector.yaml
- topics: rgb, depth or points??
-...
detection with ir:
- kinect2_bridge_ir.launch
- ground_based_people_detector_kinect2.yaml
- topics: depth or points??
-....

I appreciate the help

Thanks,
Andrés

**Comment by marketto89** [comment]
@aaramirezd 

Thank you very much for your help with the porting! Last time I tried to port OPT to Ubuntu 16.04 I had some problems with VTK and PCL, have you encountered the same problem?

Nevertheless, your detection issue seems really odd; it suggests me that there is probably a transformation problem ( something wrong with the calibration??).

Regarding the topics, the detection with ir should require:
/kinect2_head/ir_rect/camera_info 
/kinect2_head/depth_ir/points 

While the detection with rgb should require:
/kinect2_head/rgb/camera_info 
/kinect2_head/depth/points 

Tell us should you have any other issue!
Marco

**Comment by aaramirezd** [comment]
Hi Marco:

I had several problems, I will mention some that i remember since i have not yet documented it.

* opt_calibration: 
  - ros_device (Converting std::nullptr_t to bool -> porting gcc5)
* detection:
  - haardispada (ml.h to ml.hpp -> opencv 3.0 ) all ml::boost changed
* I ignored vkl lib -> I understand that ros kinetic has qt5 rendering support
* I changed some CMakeList.txt (SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11"))
* libfrennect2 and kinect2bridge latest version (all *.launch files changed -> remap topic name and param name)

![captura de pantalla de 2016-11-24 15-19-35](https://cloud.githubusercontent.com/assets/6153347/20623535/2024c034-b2ef-11e6-8aa7-5a24529a6de3.png)

In the image one of the first tests, yesterday changed "opt_calibration_results.launch -> static transform (kinect2 to kinect2_link )" and this solved the first problem.

Now, i can't do tracking with multi camera simultaneously, it seems to be switching between them

Any Ideas?

Thanks,
Andrés

PD: i did not include swissrange package

**Comment by marketto89** [comment]
@aaramirezd 

I assume you calibrated the network following [our wiki](https://github.com/OpenPTrack/open_ptrack/wiki/Pre-Calibration-File-Configuration). If this is not the case, check it and see if a new calibration solves your problem.

The other weird thing is that you installed the upstream version of libfreenect2 and iai_kinect2. Which version are you referring to? The baseline ones or our version of libfreenect2 and iai_kinect2? In case you are using the baseline versions, do our version work with ROS Kinetic? If this is the case, I would suggest you to use our versions.

Unfortunately, it is difficult for me to understand what is the real issue. Is it possible for you to share a zip with the version of OpenPTrack, iai_kinect2 and libfreenect2 you are using?

Best,
Marco

**Comment by aaramirezd** [comment]
Hi, @marketto89 

yes, I calibrated the network folllowing your wiki and everything worked fine, the problem was related to time synchronization (ntp), already solved.

I am using the libfreenect2 and iai_kinect2 baseline versions:

https://github.com/code-iai/iai_kinect2
https://github.com/OpenKinect/libfreenect2

Yes, i want to share the modified package with you, It will only take me this week to group all the modified files, according to the original package.

Thanks,
Andrés

**Comment by aaramirezd** [comment]
Hi, @marketto89 

I have already the package with modifications, I'm new to github, but I tried to make a branch between the original files and the modified ones to be able to compare them, all in a new repository.
https://github.com/aaramirezd/kinect2_network

Branch: 
- master (Original files)
- portingv1 (modified files)

I hope this helps, 

Thanks,
Andrés

**Comment by marketto89** [comment]
Thank you very much @aaramirezd 

I will try your repository in the next days!

Best,
Marco

**Comment by aaramirezd** [comment]
Hi, @marketto89 
Something did not go well with the github repository, 

i delete the previous one and upload only the modified repository
https://github.com/aaramirezd/kinect2_network

Thanks,
Andrés
