### ISSUE TITLE
Could not find "opt_define_reference_frame.launch"

### ISSUE THREAD

**Issue by wuchihsu** [OpenPTrack/open_ptrack#125]
When I did "roslaunch opt_calibration opt_define_reference_frame.launch".
The terminal gave me an error:
[opt_define_reference_frame.launch] is neither a launch file in package [opt_calibration] nor is [opt_calibration] a launch file name
Then I went to ".../open_ptrack/opt_calibration/launch/".
There was no "opt_define_reference_frame.launch".

**Comment by nanodust** [comment]
it looks to me like calibration was not built / installed properly. Try again on clean instance, take care to note any errors / fails during the process.
