### ISSUE TITLE
Kinect V2 just can't work 

### ISSUE THREAD

**Issue by SeanlUll** [OpenPTrack/open_ptrack#127]
Hi, all. I followed the Installation Guide and no Error information got. But when i roslaunch kinect2_bridge, 

Kinect V2 just can't run and still got no Error information.

Then i tried only run libfreenect2, Kinect V2 can work correctly. 

The key point is, i got no Error information through the process but Kinect can't work.

Any help would be appreciated.

**Comment by marketto89** [comment]
@SeanlUll 

could you please give us more information? Which branch are you using? Which computer/OS are you using? Could you please post your command and its output?

Thank you,
Marco

**Comment by SeanlUll** [comment]
@marketto89 

Thanks for your reply.

I thought i got no error, but after checked my terminal information line by line and found something:

```
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- checking for module 'openni-dev'
--   package 'openni-dev' not found
-- looking for PCL_COMMON
-- looking for PCL_OCTREE
-- looking for PCL_IO
-- looking for PCL_KDTREE
-- looking for PCL_SEARCH
-- looking for PCL_SAMPLE_CONSENSUS
-- looking for PCL_FILTERS
-- looking for PCL_FEATURES
-- looking for PCL_KEYPOINTS
-- looking for PCL_GEOMETRY
-- looking for PCL_SEGMENTATION
-- looking for PCL_VISUALIZATION
-- looking for PCL_OUTOFCORE
-- looking for PCL_REGISTRATION
-- looking for PCL_RECOGNITION
-- looking for PCL_SURFACE
-- looking for PCL_PEOPLE
-- looking for PCL_TRACKING
-- looking for PCL_APPS
```

But all [provided solutio](http://answers.ros.org/question/230190/openni-dev-not-found/)n still can't solve my case.

What i am trying to do is follow this [guide](https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide) to install OpenPTrack.

My computer is MR_X7Ti
Memory: 8G
Processor: Inter Core i7-6700HQ 2.6GHz x 8
Graphics: GTX1060
OS: Ubuntu LTS 14.04.5

Thanks again.

**Comment by SeanlUll** [comment]
@marketto89 

Hi, Marco. When i launch kinect v2, i got information as follows but kinect did not run successfully.

```
sean@ubuntu:~/workspace/ros/catkin/devel/lib/kinect2_bridge$ roslaunch kinect2_bridge kinect2_bridge.launch
... logging to /home/sean/.ros/log/6e357810-145e-11e7-94b9-58fb842b53ea/roslaunch-ubuntu-22396.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:40391/

SUMMARY
========

PARAMETERS
 * /kinect2_head_kinect2_bridge/sensor_id: 
 * /kinect2_head_kinect2_bridge/sensor_name: kinect2_head
 * /kinect2_head_points_xyzrgb_highres/queue_size: 2
 * /kinect2_head_points_xyzrgb_lowres/queue_size: 2
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    kinect2_head_kinect2_bridge (kinect2_bridge/kinect2_bridge)
    kinect2_head_points_xyzrgb_highres (nodelet/nodelet)
    kinect2_head_points_xyzrgb_lowres (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[kinect2_head_kinect2_bridge-1]: started with pid [22414]
process[kinect2_head_points_xyzrgb_lowres-2]: started with pid [22415]
process[kinect2_head_points_xyzrgb_highres-3]: started with pid [22416]

```

**Comment by marketto89** [comment]
@SeanlUll 

`openni-dev` is not a problem for you if you are not using a KinectV1.

Regarding the Kinect V2 launcher: are you sure you posted all the lines the command outputs? It seems to me you are missing some lines after the `started with pid` lines.

By the way, the graphic card you are using is pretty new so I suspect there could be some issue with the driver (unfortunately, we did not test the new series yet). Do you know which NVidia driver version are you using (you can see it using the `nvidia-smi` command)?

**Comment by SeanlUll** [comment]
@marketto89 

Thanks a lot !!! It works !!

CUDA 8.0 / nvidia-375-dev works great for me.
