### ISSUE TITLE
Kinect v2 not found

### ISSUE THREAD

**Issue by adielfernandez** [OpenPTrack/open_ptrack#129]
Hello, 

Trying to get the kinect2 up and running but it's not detecting at all. I followed through on everything in the installation guide up to and including the Kinect2 setup, but when I get to the point cloud test in step 7 and run 

`roslaunch kinect2_bridge kinect2_bridge.launch`

I get the following error repeating over and over until the process is stopped:

[kinect2_head_kinect2_bridge-2] process has finished cleanly
log file: /home/sensor1/.ros/log/444f64d0-2150-11e7-96e0-ac220b8ae219/kinect2_head_kinect2_bridge-2*.log
[kinect2_head_kinect2_bridge-2] restarting process
process[kinect2_head_kinect2_bridge-2]: started with pid [6953]
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenCLDepthPacketProcessor::listDevice]  devices:
  0: Quadro K5000 (GPU)[NVIDIA Corporation]
[OpenCLDepthPacketProcessor::init]  selected device: Quadro K5000 (GPU)[NVIDIA Corporation]
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 8 usb devices connected
[Freenect2Impl] found 0 devices
Error: no Kinect2 devices found!
Initialization failed!

I have tried installing the old primesense drivers and switching to freenect like in the [troubleshooting page for the kinect1](https://github.com/OpenPTrack/open_ptrack/wiki/Troubleshooting/), but still nothing. Any ideas on what could be wrong?

**Comment by marketto89** [comment]
@adielfernandez 

it seems that the Kinect v2 is not detected by your system. Unfortunately, the Quadro GPUs [are not officially supported by OpenPTrack](https://github.com/OpenPtrack/open_ptrack/wiki/Supported-Hardware), even if I expect they should work.

Are you sure no errors were raised by the kinect2_install.sh script? I suggest you to try line by line that script and see if there is something wrong. 

By the way, if you are using a Kinect v2 there is no need of freenect which was used just for the Kinect v1.

**Comment by adielfernandez** [comment]
Thanks for your reply. I figured the freenect switch was just for the v1 but attempted it anyway. No errors were thrown after running the kinect2_install.sh script. I still haven't been able to get one machine to recognize the kinect2 but I've switched that machine from a client to the master so I could move on to other issues. 

I can understand how the GPU is used for computational support but will an unsupported GPU actually stop the Kinect from being recognized? I figured it had to be something else.

**Comment by marketto89** [comment]
@adielfernandez,

the different GPU should not be the problem, but that particular family is not tested, so I cannot be sure that the problem is not GPU-related. 

I asked you to check the kinect2_install output, because the errors it can generate could be silent (i.e. the script does not stop to run in case of an error). In particular, the script is in charge of installing the correct libusb patch in your system. If this fails, the Kinect v2 will not be detected by your system. 

From your [other issue](#130), I can understand that you have been able to make the Kinect work. Is this the case?

**Comment by adielfernandez** [comment]
Hello, sorry for the delayed reply. I was never able to get the Kinect2 running on a specific computer. Due to time constraints I used the computer that was unable to see the kinect2 as the master/tracking node and used my other two as detection nodes. If I need to use that computer again/or if I run into this issue with another one I will be sure to looking to dissecting the kinect2_install script. Thank you!
