### ISSUE TITLE
Intel Realsense ZR300 camera with Intel NUC7i7BNH mini PC

### ISSUE THREAD

**Issue by giantmonster** [OpenPTrack/open_ptrack#133]
Hi,
In that two of the cameras listed as supported hardware are no longer available, I'm working on a configuration that uses Intel Realsense ZR300 camera with Intel NUC7i7BNH mini computer. I'd like to get a driver for the ZR300 to work with openPTrack. Can you offer some guidance on this, if possible?
Thanks,
Mark

**Comment by marketto89** [comment]
Hey @giantmonster 

Adding a new sensor is not trivial at all. I suggest you to familiarize with the ROS middleware. 
These are the main points you should cover:

- you should able to stream ROS topics using your camera. In particular, for the ZR300 you should try [its ROS wrapper](http://wiki.ros.org/realsense_camera).
- you should able to generate a point cloud. Have a look at what we do for the Kinect v2 [here](https://github.com/OpenPTrack/iai_kinect2/blob/master/kinect2_bridge/launch/kinect2_bridge.launch#L17-L25).
- you should write a detector_depth_yoursensor.launch which will be used whenever you want to use your  sensor. Have a look to the [Kinect v2 version](https://github.com/OpenPTrack/open_ptrack/blob/master/detection/launch/detector_depth_kinect2.launch) as an example 
- you should update the [listener.py](https://github.com/OpenPTrack/open_ptrack/blob/development/opt_calibration/apps/listener.py) file which is in charge to generate the detection launchers you need for launching the sensor on each detection node.
