### ISSUE TITLE
minimum Kinect2 Rosbag 

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#134]
Tracking and detection is working quite well using defaults and rqt_configure - yet I'm trying to record a physical sequence of people with a single Kinect 2 so I may fine-tune the tracking parameters further for a site without needing people to walk around for hours :) 

per [tips and tricks](https://github.com/OpenPTrack/open_ptrack/wiki/Tips-and-Tricks), a kinect records with just:
```
<kinect_name>/depth_registered/image_raw
<kinect_name>/depth_registered/camera_info
<kinect_name>/rgb/image_raw
<kinect_name>/rgb/camera_info
<kinect_name>/depth_registered/disparity
```

I can find potential equivalents via rostopic list:

```
<kinect_name>/depth_registered/image_raw -> /kinect2_head/depth/image
<kinect_name>/rgb/image_raw -> /kinect2_head/rgb/image | /kinect2_head/rgb_rect/image | /kinect2_head/depth_rect/image
/kinect2_head/rgb/camera_info

```
but not for
```
<kinect_name>/depth_registered/disparity = ?
<kinect_name>/depth_registered/camera_info = ?
```

anyone know offhand ? 

meanwhile I'm just recording the full rostopic tree under 'kinect_2' - but files are likely far larger than necessary.

**Comment by marketto89** [comment]
Hey @nanodust 

yes, if you record everything the final rosbag will be extremely large. Moreover, it is very likely that the framerate of your topics in the bag will be way lower than the actual sensor ones. 

Before answering your question: are you using the development or master branch of OpenPtrack?

**Comment by nanodust** [comment]
using master branch ! 

indeed, i recorded everything - but then I realized I'm missing some notes on how to actually start ros w/o sensor, and use the rosplay or rqt_bag to replay the stream. 

again the point here is just to have a single person perform a walk/pattern, and then loop that recording while using rqt_reconfigure to fine-tune the parameters. 

all I'd know to do at this point would be to go back to original Kinect, get the full test cycle working, then move back to Kinect2 and just try everything. 

hardly efficient, open to any other ideas :)

**Comment by marketto89** [comment]
As far as I know the master branch with the Kinect v2 uses IR-colored point cloud.

So, if you do not need the RGB image for other goals, what I suggest you to do is to record just depth, ir and ir/camera_info topics. This information should be enough for the detector to work. 

Once you recorded the bag you should launch the openPTrack detector and tracker with the command `roslaunch tracking detection_and_tracking_kinect2.launch` paying attention to [comment out line 5 of detector_depth_kinect2.launch](https://github.com/OpenPTrack/open_ptrack/blob/master/detection/launch/detector_depth_kinect2.launch#L5) (you do not need the sensor anymore; remember to uncomment the line once you finished to test!). Then, you can play the bag with `rosbag play --pause --clock <bag_name.bag>`. The --pause should allow you to change the parameters with `rqt_reconfigure` without loosing any frame recorded, while the --clock should replace the time information in the header of your recorded messages with the current one (this is for avoiding synchronization or OLD_DATA errors). Once you set the parameters you can just press space and the bag will start to be executed. 
I always had troubles using `rqt_bag` (for everything which is not just looking the fps of the recorded bag), so I feel to suggest you not to use it.

Can you please post the graph resulting from `rqt_graph` while you are running the single-camera system? It can be useful to understand the `rosbag record` you should use.

**Comment by nanodust** [comment]
Thank you !!! I will try all of this on Monday and write back.

**Comment by marketto89** [comment]
You're welcome! 

I forgot to say that in `rqt_graph` you should have this configuration:
![rqt_graph_conf](https://user-images.githubusercontent.com/5969233/27247403-ead58a72-52ac-11e7-90b6-83f135258254.png)

Let us know!

**Comment by nanodust** [comment]
Here is the rqt_graph of all nodes/topics of the single camera kinect2 system. 

![rosgraph_single_kinect2](https://user-images.githubusercontent.com/65142/27310007-c9301cda-551c-11e7-99a9-db85ecbd4ae5.png)

I'm trying the rosbag... will post results...

**Comment by nanodust** [comment]
bingo ! the following commands work:

`rosbag record -b0 /tf /kinect2_head/depth/camera_info /kinect2_head/depth/image /kinect2_head/depth/image/compressedDepth /kinect2_head/depth_highres/camera_info /kinect2_head/depth_highres/image /kinect2_head/depth_highres/image/compressedDepth /kinect2_head/depth_ir/points /kinect2_head/depth_lowres/camera_info /kinect2_head/depth_lowres/image /kinect2_head/depth_lowres/image/compressedDepth /kinect2_head/depth_rect/camera_info /kinect2_head/depth_rect/image /kinect2_head/depth_rect/image/compressedDepth /kinect2_head/ir/camera_info /kinect2_head/ir/image /kinect2_head/ir/image/compressed /kinect2_head/ir_rect/camera_info /kinect2_head/ir_rect/image /kinect2_head/ir_rect/image/compressed /kinect2_head/ir_rect_eq/camera_info /kinect2_head/ir_rect_eq/image /kinect2_head/ir_rect_eq/image/compressed`

then to play back, comment out [line 5](https://github.com/OpenPTrack/open_ptrack/blob/master/detection/launch/detector_depth_kinect2.launch#L5) and:

`roslaunch tracking detection_and_tracking_kinect2.launch `

then

`rosbag play --pause --clock -l <bag file name> `

then
 
`rosrun rqt_reconfigure rqt_reconfigure`

and indeed, the sensor track will loop, and allow calibration. 

This is fantastic ! Extremely useful for tuning detection and tracking for a site. 

Thanks for the feedback !!!

**Comment by nanodust** [comment]
I will use this process as I calibrate this system, and post any improvements back here, to ultimately make their way to the documentation. 

For example, I suspect the bag still contains more topics than we actually need (30 seconds is about 7 GB!) but as it works, I'll leave optimization to after I get the installation working well. 

thanks again !

**Comment by marketto89** [comment]
No problem! 

to extract the minimum set of topics, I would record just the following: 
   ```
/../ir_rect/camera_info 
   /../ir_rect_eq/image  
   /../depth_rect/image
```

If available, record the bag on a SSD and remember to use an infinite buffer. I would do something like this:
`rosbag record -b0 -O/<somewhere_in_your_ssd>/bag_name.bag /kinect2_head/ir_rect/camera_info /kinect2_head/ir_rect_eq/image /kienct2_head/depth_rect/image`

You can also keep an eye on the disk usage with `watch -d -n0.5 df` on another terminal

Thank you very much for your feedback! We will soon update also the wiki with this information!

**Comment by nanodust** [comment]
only now I notice a related issue [here](https://github.com/OpenPTrack/open_ptrack/issues/128)

**Comment by nanodust** [comment]
I will try the minimum topics today and confirm.

**Comment by nanodust** [comment]
interesting

`rosbag record -b0 /tf /kinect2_head/ir_rect/camera_info /kinect2_head/ir_rect_eq/image /kinect2_head/depth_rect/image
`
then commenting out line 5 of detector_depth_kinect2.launch and:

```
roslaunch tracking detection_and_tracking_kinect2.launch
rosbag play --pause --clock <filename.bag>
```
does not allow detections or tracks.
I can see the topics, verify the data is there - but seems I'm missing something detection needs. 

I thought it may be due to ground_estimation_mode: 0 vs 3 - but same effect either way. 

I'll play around a bit and see if i can find the missing topic/s. 

Encouraging, though, as the same duration has about 1/14 the file-size from yesterday's test :)

**Comment by marketto89** [comment]
Mmmh, probably you need also the /tf and /tf_static in your rosbag command.

**Comment by nanodust** [comment]
Hello, 

While we did not converge on a  'minimal topic' set for playback & detection, doing the 'huge' command far abov ewith the 18 or so topics will indeed allow detection. The only drawback is the filesize is rather large.

As for 2 cameras - I believe you can just record the topics for both cameras, in a single command, from your master.

**Comment by dagelabi** [comment]
Thanks @nanodust 

I tried creating a rosbag with all those topics, but when I run it I get those errors

`[ERROR] [1525105249.325721546]: transform exception: Lookup would require extrapolation into the past.  Requested time 1525104167.803560004 but the earliest data is at time 1525105239.487810510, when looking up transform from frame [kinect_camera_2_ir_optical_frame] to frame [world] If you are seeing just one error like this do not worry, I am probably working!`

```
Warning: TF_OLD_DATA ignoring data from the past for frame kinect_camera_1_ir_frame at time 1.5251e+09 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.16/src/buffer_core.cpp
```

What I did is :  
1 ) Running `roslaunch  opt_calibration sensor_<nodename>.launch` on each machine


2) In a new terminal windows I ran the record
`rosbag record -b0 /tf /tf_static /kinect_camera_1/depth/camera_info /kinect_camera_1/depth/image /kinect_camera_1/depth/image/compressedDepth /kinect_camera_1/depth_highres/camera_info /kinect_camera_1/depth_highres/image /kinect_camera_1/depth_highres/image/compressedDepth /kinect_camera_1/depth_ir/points /kinect_camera_1/depth_lowres/camera_info /kinect_camera_1/depth_lowres/image /kinect_camera_1/depth_lowres/image/compressedDepth /kinect_camera_1/depth_rect/camera_info /kinect_camera_1/depth_rect/image /kinect_camera_1/depth_rect/image/compressedDepth /kinect_camera_1/ir/camera_info /kinect_camera_1/ir/image /kinect_camera_1/ir/image/compressed /kinect_camera_1/ir_rect/camera_info /kinect_camera_1/ir_rect/image /kinect_camera_1/ir_rect/image/compressed /kinect_camera_1/ir_rect_eq/camera_info /kinect_camera_1/ir_rect_eq/image /kinect_camera_1/ir_rect_eq/image/compressed /kinect_camera_2/depth/camera_info /kinect_camera_2/depth/image /kinect_camera_2/depth/image/compressedDepth /kinect_camera_2/depth_highres/camera_info /kinect_camera_2/depth_highres/image /kinect_camera_2/depth_highres/image/compressedDepth /kinect_camera_2/depth_ir/points /kinect_camera_2/depth_lowres/camera_info /kinect_camera_2/depth_lowres/image /kinect_camera_2/depth_lowres/image/compressedDepth /kinect_camera_2/depth_rect/camera_info /kinect_camera_2/depth_rect/image /kinect_camera_2/depth_rect/image/compressedDepth /kinect_camera_2/ir/camera_info /kinect_camera_2/ir/image /kinect_camera_2/ir/image/compressed /kinect_camera_2/ir_rect/camera_info /kinect_camera_2/ir_rect/image /kinect_camera_2/ir_rect/image/compressed /kinect_camera_2/ir_rect_eq/camera_info /kinect_camera_2/ir_rect_eq/image /kinect_camera_2/ir_rect_eq/image/compressed`


3) On the master I ran  `roslaunch tracking tracking_node.launch`


4) On the slaves I ran `roslaunch detection detection_node_<nodename>.launch` ( I commented the  `<include file="$(find kinect2_bridge)/launch/kinect2_bridge_ir.launch">` )

5) Then` rosbag play --pause --clock -l <bag file name>`

**Comment by nanodust** [comment]
I don't have my system set up, can't quick verify...  comments right now:

i thought setting --clock prevents this time error ? Are you sure you want -l option ? ([limit](http://wiki.ros.org/rosbag/Commandline)) ? I'd give it a shot without.

**Comment by dagelabi** [comment]
Thanks @nanodust 
The -l option in the rosbag play command enables the loop ! The limit option is for rosbag record. In any case, I tried removing the -l and the --clock and it still not working.

I'm using OpenPTrack V2 so maybe it's related to the new version.

**Comment by dagelabi** [comment]
![rosgraph](https://user-images.githubusercontent.com/16769795/39445288-97dc77be-4c88-11e8-998c-ef468bac0a55.png)

**Comment by nanodust** [comment]
Other than my V1 graph had no children for /tf, vs yours having quite a few... I don't see much different in the topics. I'm likely not much help here until I get a v2 system up and running.

**Comment by dagelabi** [comment]
Thank you for your time @nanodust  !
