### ISSUE TITLE
Imager calibration inaccurracy

### ISSUE THREAD

**Issue by jburkeucla** [OpenPTrack/open_ptrack#15]
In our largest multi-node installation, the new detection visualization shows what appears to be significant calibration differences across the multiple imagers, potentially leading to tracking inaccuracy.  One hypothesis is that the pairwise calibration of nearby imagers causes error to accumulate between imagers that are not next to each other in the calibration process but observe the same area.

**Comment by mmunaro** [comment]
Closing this issue.
