### ISSUE TITLE
[Hardware Advice] Kinect v2 Placement

### ISSUE THREAD

**Issue by vkedwardli** [OpenPTrack/open_ptrack#165]
Hi all, I'm planning to cover an area of 10.7m x 8.6m, from my initial calculation this would requires 4 Kinects v2 in total (correct me if I'm wrong)

So I'm wondering, which is the better way to place them in the area?
![Image](https://i.imgur.com/gmpYocM.png)

My first thought was the left arrangement, the right arrangement is try to overlap as much as area I could.

This will be a dark room, with floor projection, hope this won't affect the infra red camera, am I correct that the color image camera isn't used at all?

Thanks a lot

**Comment by vkedwardli** [comment]
Or is 2 cameras enough?
![Image](https://i.imgur.com/mPcqBCt.png)

(The furthest point is 11.6m from camera, I'm drawing it with a 10m radius according to wiki)

**Comment by dthirst** [comment]
which setup did you end up using? did using two kinects work?

**Comment by vkedwardli** [comment]
@dkeih sorry I didn't use OpenPTrack since there wasn't any support, I just used 2 LIDARs which had a great result

**Comment by dthirst** [comment]
@vkedwardli could you point me towards what software solution you used to track the people and what sensors you used? I am working on a project with a very similar conditions

**Comment by vkedwardli** [comment]
2 LIDAR placed at corners and TUIO for touch input, rendering is using HTML5 canvas. You will need special software to convert the LIDAR information to TUIO
