### ISSUE TITLE
[Hardware question] Is it possible to use Intel Realsense on the camera of your package?

### ISSUE THREAD

**Issue by GyeoreLee** [OpenPTrack/open_ptrack#167]
Hi, 

I want to use your packages for my research project.
But in our environment, We consider to use Intel® RealSense™ Depth Camera D435.
Is it possible to use Intel RealSense on the camera of your package?
If not, do you plan to expand the available cameras?

Thank you.

**Comment by jburkeucla** [comment]
We are looking at how to do this; it’s just a question of available developer cycles.  We hope to address by October.
Jeff

**Comment by inders** [comment]
Any update on support of Intel Real Sense or any other suggested workout to use them would be very helpful.

**Comment by msacco22** [comment]
Hi, by any chance was there an update on this?

**Comment by SimeonOA** [comment]
Hi please refer to the replies to [Issue 51](https://github.com/OpenPTrack/open_ptrack_v2/issues/51) here. 

Thanks 

Simeon
