### ISSUE TITLE
Writing a wrapper for Orbbec Astra

### ISSUE THREAD

**Issue by joaocandre** [OpenPTrack/open_ptrack#174]
After stumbling into [this issue/request](https://github.com/OpenPTrack/open_ptrack/issues/76#issue-137501183), I developed an interest to experiment running OpenPTrack on an Orbbec Astra sensor. How would one go about writing a wrapper for this device?

**Comment by bsubbaraman** [comment]
Hi @joaocandre, thanks for your interest! This repo is for OpenPTrack version 1, which has been deprecated. Would you mind opening this issue (and all further issues) over on [version 2](https://github.com/OpenPTrack/open_ptrack_v2)? Thanks!

**Comment by joaocandre** [comment]
@bsubbaraman Sorry, my mistake. I will do that.
