### ISSUE TITLE
Kinect driver does not appear to load on fresh installation

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#19]
When following the installation instructions verbatim in the wiki on a clean 14.04 installation

everything appears to install fine. 

the first sign of trouble is when testing a single kinect:

roslaunch detection openni.launch

[ INFO] [1414031641.954680151]: No devices connected.... waiting for devices to be connected

the bashrc and env variable KINECT_DRIVER is indeed openni

/opt/ros/indigo/lib indeed contains compiled libopenni_driver.so and libopenni_nodelet

this is a system that was previously working perfectly in 13.04, but we wanted to just reformat and start fresh with 14.04, and it appears the openni does not work as expected. 

we did not dig in futher to check udev or etc - it should have 'just worked' as it has before. 

did something change upstream w/ ros ? there does not seem to to be the same error requiring the force install... perhaps that is now causing issues? 

we just did this on 3 machines, and all of them were previously working in 13.04, and all of them are now experiencing this same issue.

**Comment by johnnyonthespot** [comment]
Fixed my problem! I'm glad I ran into this thread.
Using: Ubuntu 14.04, ros-indigo
