### ISSUE TITLE
SwissRangerConfig.h not found error

### ISSUE THREAD

**Issue by pdepeche** [OpenPTrack/open_ptrack#30]
1) "Building CXX object open_ptrack/swissranger_camera/CMakeFiles/swissranger_camera.dir/src/sr.cpp.o
/home/hal/catkin_ws/src/open_ptrack/swissranger_camera/src/sr.cpp:53:50: fatal error: swissranger_camera/SwissRangerConfig.h: No such file or directory
 #include <swissranger_camera/SwissRangerConfig.h>"

This error is during the very last command, "catkin_make" or "catkin_make --force-cmake", of entire installation procedure.

This error dissapears if I open new terminal window and re-run the script, and then open_ptrack package (program) runs and executes just fine.

2) Perhaps, this is related to earlier warning message:
"#### Running command: "cmake /home/hal/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/home/hal/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/hal/catkin_ws/install" in "/home/hal/catkin_ws/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/hal/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/hal/catkin_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/hal/catkin_ws/devel;/opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/hal/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.9
-- BUILD_SHARED_LIBS is on
WARNING: package "swissranger_camera" should not depend on metapackage "ros" but on its packages instead
WARNING: package "swissranger_camera" should not depend on metapackage "image_common" but on its packages instead"

3) This should not be, I think, related to the fact that I modified the scripts to work with my current catkin workspace directory, ~/catkin_ws. Scripts are below:

===== open_ptrack_install_1.sh begins:==========
for FILE in $(find / -name '.catkin_workspace' 2>/dev/null); do
    CAT_WS="${FILE%.[^.]*}"
    MY_CATKIN_WS_DIR="${CAT_WS%/}"
done

source /opt/ros/indigo/setup.bash
source $MY_CATKIN_WS_DIR/devel/setup.bash

ROS_PACKAGES="python-rosinstall ros-$ROS_DISTRO-robot-state-publisher ros-$ROS_DISTRO-cmake-modules ros-$ROS_DISTRO-freenect-stack ros-$ROS_DISTRO-openni-launch ros-$ROS_DISTRO-camera-info-manager-py"

sudo apt-get install $ROS_PACKAGES

echo "export KINECT_DRIVER=freenect" >> ~/.bashrc
echo "export LC_ALL=C" >> ~/.bashrc
export KINECT_DRIVER=freenect
export LC_ALL=C

source /opt/ros/indigo/setup.bash
source $MY_CATKIN_WS_DIR/devel/setup.bash

cd $MY_CATKIN_WS_DIR/src
git clone https://github.com/OpenPTrack/open_ptrack.git
cd open_ptrack/scripts
sudo chmod +x *.sh

./ceres_install_trusty.sh

cd $MY_CATKIN_WS_DIR/src
git clone https://github.com/iaslab-unipd/calibration_toolkit
cd calibration_toolkit
git fetch origin --tags
git checkout tags/v0.2

cd ~
mkdir libfreenect
cd libfreenect
git clone https://github.com/OpenKinect/libfreenect.git
cd libfreenect
git checkout tags/v0.4.0

mkdir build
cd build
cmake -L ..
make

sudo mv ~/libfreenect/libfreenect/build/lib/fakenect/* /opt/ros/indigo/lib/fakenect/
sudo mv ~/libfreenect/libfreenect/build/lib/libfreenect* /opt/ros/indigo/lib/
sudo mv ~/libfreenect/libfreenect/build/src/libfreenect.pc /opt/ros/indigo/lib/pkgconfig/
sudo mv ~/libfreenect/libfreenect/include/libfreenect.h /opt/ros/indigo/include/libfreenect/libfreenect.h
sudo mv ~/libfreenect/libfreenect/include/libfreenect_registration.h /opt/ros/indigo/include/libfreenect/libfreenect-registration.h
sudo mv ~/libfreenect/libfreenect/wrappers/cpp/libfreenect.hpp /opt/ros/indigo/include/libfreenect/libfreenect.hpp
sudo mv ~/libfreenect/libfreenect/wrappers/c_sync/libfreenect_sync.h /opt/ros/indigo/include/libfreenect/libfreenect_sync.h
cd $MY_CATKIN_WS_DIR/src
git clone https://github.com/ros-drivers/freenect_stack.git
sudo rm -R ~/libfreenect

if [ -d "~/Downloads" ]
then 
	echo ""
else
	mkdir -p ~/Downloads
fi 
cd $MY_CATKIN_WS_DIR/src/open_ptrack/scripts
./mesa_install.sh

source /opt/ros/indigo/setup.bash
source $MY_CATKIN_WS_DIR/devel/setup.bash
cd $MY_CATKIN_WS_DIR
catkin_make --pkg calibration_msgs
catkin_make --pkg opt_msgs
================ open_ptrack_install_1.sh end =============================

================== open_ptrack_install_2.sh begins: =================
for FILE in $(find / -name '.catkin_workspace' 2>/dev/null); do
    CAT_WS="${FILE%.[^.]*}"
    MY_CATKIN_WS_DIR="${CAT_WS%/}"
done
source /opt/ros/indigo/setup.bash
source $MY_CATKIN_WS_DIR/devel/setup.bash
export KINECT_DRIVER=freenect
export LC_ALL=C
cd $MY_CATKIN_WS_DIR
catkin_make --force-cmake
============== end open_ptrack_install_2.sh ====================================

**Comment by lucashn** [comment]
I am having this issue too with Ubuntu 14.04.2. But the error does not goes away when repeating the process.
