### ISSUE TITLE
detections float above the ground plane and tracks

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#31]
frankly this is nearly a feature and not a bug - as it's easier to separate detections from tracks when debugging splitting / detection ranges

but it's likely not intentional and should probably be addressed. 

https://www.youtube.com/watch?v=ecX2AhjLGB8

**Comment by mmunaro** [comment]
This issue was likely due to a calibration bug solved with 046a7aabe403a339e87517b1c9393b8840e1c158. Closing this issue.
