### ISSUE TITLE
Rviz Crashes During Calibration

### ISSUE THREAD

**Issue by lthursdayl** [OpenPTrack/open_ptrack#34]
Rviz crashes during calibration and cannot be recovered. We would like a way to recover the GUI .

 INFO] [1422995489.713022696]: [/FrontLK] checkerboard detected
[ INFO] [1422995493.011323150]: [/FrontRR] checkerboard detected
[ INFO] [1422995493.012086378]: Optimizing...
[ INFO] [1422995497.783380796]: -----------------------------------------------
[rviz-1] process has died [pid 8890, exit code -11, cmd /opt/ros/indigo/lib/rviz/rviz -d /home/remap-dev/workspace/ros/catkin/src/open_ptrack/opt_calibration/conf/opt_calibration.rviz __name:=rviz __log:=/home/remap-dev/.ros/log/6fd65f42-abe0-11e4-87c7-0060e05b0a32/rviz-1.log].
log file: /home/remap-dev/.ros/log/6fd65f42-abe0-11e4-87c7-0060e05b0a32/rviz-1*.log
[ INFO] [1422995500.667932911]: [/RearLMK] checkerboard detected
[ INFO] [1422995501.154173362]: -----------------------------------------------
[ INFO] [1422995503.106417417]: [/RearLK] checkerboard detected
[ INFO] [1422995503.609587894]: [/RearRK] checkerboard detected
[ INFO] [1422995504.112466378]: -----------------------------------------------
[ INFO] [1422995511.501636713]: [/RearRMK] checkerboard detected
[ INFO] [1422995514.425723373]: -----------------------------------------------
[ INFO] [1422995515.681095734]: [/RearRMK] checkerboard detected
[ INFO] [1422995517.782086911]: -----------------------------------------------
[ INFO] [1422995521.477959621]: [/FrontRMK] checkerboard detected
[ INFO] [1422995523.140388522]: [/FrontRR2] checkerboard detected

**Comment by nanodust** [comment]
Yes, it crashes every single time

Just start rviz & pull up config

**Comment by mmunaro** [comment]
The right configuration file to load when doing calibration is this:
open_ptrack/opt_calibration/conf/opt_calibration.rviz
