### ISSUE TITLE
Need a mechanism/instructions to backup and restore calibrations across all nodes

### ISSUE THREAD

**Issue by jburkeucla** [OpenPTrack/open_ptrack#35]
This would greatly help troubleshoot / refine our calibration process.

**Comment by mmunaro** [comment]
Instructions:
The (extrinsic) calibration information is stored in this file:
~/workspace/ros/catkin/open_ptrack/opt_calibration/conf/camera_poses.yaml

You can save a copy of this file with the name you prefer and use these instructions to restore it:
1) substitute this file with the calibration file you want to restore:
~/workspace/ros/catkin/open_ptrack/opt_calibration/conf/camera_poses.yaml
2) repeat Step 2 of the network calibration guide:
https://github.com/OpenPTrack/open_ptrack/wiki/Camera-Network-Calibration#2-create-files-for-multi-sensor-people-tracking

Now the old calibration has been restored.

NB: this process does not restore the calibration refinement procedure, thus it should be repeated.

This documentation should be moved to the Wiki.

**Comment by mmunaro** [comment]
Instruction moved to the Wiki:
https://github.com/OpenPTrack/open_ptrack/wiki/Tips-and-Tricks#restore-previous-calibration
