### ISSUE TITLE
ground_detection...Kinect2.yaml loaded instead of Kinect1.yaml for Kinect v1

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#38]
Matteo, 

small bug noted yesterday in 'development' branch when testing:

the Kinect settings we had in Kinect1.yaml were not loading when Kinect1 loaded... they'd load the preferences/parameters from the Kinect2, regardless of whether sensor was Kinect 1 or Kinect 2. 

We fixed it just by putting settings in Kinect 2 :) but obviously we should fix this for future. 

thanks !!!

**Comment by mmunaro** [comment]
Fixed with commit 9f4dc07d937029a373b67fb4fb0762a274864656.
