### ISSUE TITLE
NDN-OPT Publisher Intermittent Crashing 

### ISSUE THREAD

**Issue by lthursdayl** [OpenPTrack/open_ptrack#40]
the NDN-OPT publisher is crashing intermittently. Here is the terminal output when the publisher crashes:

[ INFO] [1429288855.950995112]: published track 157 with name /ndn/edu/ucla/remap/opt/node0/1429229219/tracks/157/544 json: {"sec":1429288855,"nsec":942201020,"id":157,"x":1.21061,"y":-0.934918,"z":1.53415}
[ INFO] [1429288855.989881029]: published track 157 with name /ndn/edu/ucla/remap/opt/node0/1429229219/tracks/157/545 json: {"sec":1429288855,"nsec":975663912,"id":157,"x":1.21096,"y":-0.933248,"z":1.53547}
[ERROR] [1429288856.066322969]: got exception: SocketTransport error in recv
[ros2ndn_converter-1] process has finished cleanly
log file: /home/remap/.ros/log/7d2f0cba-dff3-11e4-a008-78d004209f8c/ros2ndn_converter-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by nanodust** [comment]
I wonder if this is still happening. I've been publishing UDP for past week, detections seem fine, logs don't indicate any crashing.

**Comment by jburkeucla** [comment]
Fixed.
