### ISSUE TITLE
Multi-Calibration Attempts With Same Calibration 

### ISSUE THREAD

**Issue by lthursdayl** [OpenPTrack/open_ptrack#42]
We would like a way to run the calibration refinement process multiple times under the same calibration. An example would be having a way to remove the current calibration refinement information so another calibration refinement process can be run.

**Comment by mmunaro** [comment]
It already works like that. If you re-run the calibration refinement, the previous refinement is not taken into account. 
If you don't want tracking to use the refinement results, you can set to "false" the "calibration_refinement" parameter in "open_ptrack/tracking/conf/tracker_multicamera.yaml" or remove the "registration_..." files in the "open_ptrack/opt_calibration/conf" folder.

**Comment by lthursdayl** [comment]
Really? We were operating thinking that calibration refinement can only be performed once per calibration. Just to confirm, calibration refinement can be run as many times as deemed necessary per calibration? If so, great.

**Comment by mmunaro** [comment]
Yes, I confirm on this. The refinement procedure saves different files wrt calibration, thus the results of the standard calibration procedure are not overwritten and can still be used without refinement.

**Comment by lthursdayl** [comment]
Great, thanks.
