### ISSUE TITLE
installation seems to require SR header

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#44]
the question is:

should there be a libmesa dependency in the general installation instructions ? 

ie - i'm not planning on installing the mesa imager, but i still had to install the mesa library for OPT to compile. 

meanwhile I updated the driver path in installation scripts.... so for now it's working again. 

details:

from wiki install guide - https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide

1. ok 
2. ok 
3. ok - nope. 

fails. 

Per N.B - I try again. (though i've not had to do this in a while). Same error. I try again. same error. 

this is on a clean 14.04 install w/ same specs. I've used Kinect One SDK on same machine via dual boot - full framerate, no USB 3.0 problems that have occasionally made building a machine for Kinect One work challenging. Everything works well. 

full log is here http://pastebin.com/HgLb36Ym

yet error is: 

h:5:23: fatal error: libMesaSR.h: No such file or directory
 #include <libMesaSR.h>
                       ^
compilation terminated.

error seems related to swiss ranger - yet, I am not installing a swiss ranger. should the SR be a dependency ? 

my goal is new kinect, but i'm not at that step yet :) 

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

$ uname -a
Linux worker 3.16.0-43-generic #58~14.04.1-Ubuntu SMP Mon Jun 22 10:21:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nanodust** [comment]
Looking deeper, the step that failes is in ~/scripts/mesa_install.sh - the URL now points to 'heptagon industries' instead of the 64 bit binary :)

**Comment by nanodust** [comment]
instead switching to the URL commented out (32buit ) and changing to 64 bit.... seems to work. but their site (and business model?) seems to be changing, perhaps we should host this elsewhere if this is indeed a depedency. 

http://downloads.mesa-imaging.ch/dlm.php?fname=./customer/driver/libmesasr-dev-1.0.14-747.amd64.deb

**Comment by nanodust** [comment]
no luck - 

[ 76%] Built target haar_disp_ada
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libmesasr.so when searching for -lmesasr
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libmesasr.so when searching for -lmesasr
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../libmesasr.so when searching for -lmesasr
/usr/bin/ld: skipping incompatible //usr/lib/libmesasr.so when searching for -lmesasr
/usr/bin/ld: cannot find -lmesasr
collect2: error: ld returned 1 exit status
make[2]: *** [/home/worker/workspace/ros/catkin/devel/lib/swissranger_camera/swissranger_camera] Error 1
make[1]: *** [open_ptrack/swissranger_camera/CMakeFiles/swissranger_camera.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 77%] [ 78%] Built target calibration_msgs_generate_messages

indeed- despite the URL working, this is a 32 bit library. 

worker@worker:~$ objdump -f /usr/lib/libmesasr.so

/usr/lib/libmesasr.so:     file format elf32-i386
architecture: i386, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x0000ba50

hmm.

**Comment by nanodust** [comment]
Actually... re-opening. 

Why do we have an SR dependency, when I'm not intending to use or install, a mesa imager ?

**Comment by nanodust** [comment]
this seems to have been fixed w/ https://github.com/OpenPTrack/open_ptrack/pull/43 ?

**Comment by mmunaro** [comment]
Actually that was a first trial to remove that dependency, but it would have implied to have two different repositories not synced to each other.
For this reason, we will probably provide a different solution to this, such as a conditional compilation.

**Comment by marketto89** [comment]
Problem fixed with commit 0071b4c57d70017cd32e43401ca9e8e8c8dfcd87

**Comment by mmunaro** [comment]
Closing this issue since now the problem has been fixed by some changes to a CMakeLists..
