### ISSUE TITLE
Kinect 2 does not work / no TF

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#46]
from wiki install guide - https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide
1. ok 
2. ok 
3. ok
4. n/a (not using kinect 1)
5. n/a (not using PG)
6. Kinect V2
6.1 OK
6.2 OK
6.3 OK
6.4 OK
7.1 Fail

Set the Fixed Frame as:
 /kinect2_head_rgb_optical_frame

there is no topic for fixed_frame - instead,  i have error in rviz:

"No tf data.  Actual error: Fixed Frame [map] does not exist"

so, let's at least see if there is a kinect point cloud... adding /kinect2_head/depth_lowres/points

NO

gives me a status error:

For frame [/kinect2_head_rgb_optical_frame]: Fixed Frame [map] does not exist

how about other kinect 2 topics ?  adding /kinect2_head/depth_lowres/image
appears fine, full frame rate

~$  rostopic hz /kinect2_head/depth_lowres/points 

subscribed to [/kinect2_head/depth_lowres/points]
average rate: 15.041
	min: 0.063s max: 0.070s std dev: 0.00180s window: 15
average rate: 15.009
	min: 0.063s max: 0.070s std dev: 0.00182s window: 30
...

(In windows 8.1 Kinect SDK on this same machine (dual boot) I get 30 fps in their connection test)

Continuing... 

 roslaunch tracking detection_and_tracking_kinect2.launch

everything launches - i see the image - however there are no detections. 

is the transform error an easy fix (or revealing problem) ? 

Everything else seems fine - Kinect 2 *almost* works... 

any ideas ? 

not sure where to start debugging this.

**Comment by mmunaro** [comment]
Kinect 2 is working as seen with toostopic hz.
If you see the error "Fixed Frame [map] does not exist", it looks like the Fixed Frame is still set to "map", the default one.
Try again to set it to "kinect2_head_rgb_optical_frame", then press Enter.

**Comment by nanodust** [comment]
OK ! 

good call. However, the 'fixed frame: map' combo-box was only populated with 'map'. I could not click-and-select any other topic. 

manually copying in your topic 'kinect2_head_rgb_optical_frame' name from your post, pasting it over 'map', and hitting enter... worked. 

i'll update documentation.

**Comment by nomi321** [comment]
can you please elaborate how did you solve this .. i m not able to do this ... thanks
