### ISSUE TITLE
roslaunch kinect2_bridge kinect2_bridge.launch error: clGetPlatformIDs

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#47]
I've seen this before; but I forget how to fix. 

Everything installed fine per instructions. I was able to see the kinect 2 point cloud in rviz. 

i then tried next step/7.2:  roslaunch tracking detection_and_tracking_kinect2.launch

however, it did not start - i thought perhaps because the launch command is re-launching the kinect_bridge, which was already open....

to be safe / start all processes from scratch, i rebooted. 

to my suprise, i got a CLPlatformError. 

i re-tried installing the non-nvidia... 

sudo apt-get install ocl-icd-opencl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
ocl-icd-opencl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

no luck, still fails:

cat /etc/OpenCL/vendors/nvidia.icd 

libnvidia-opencl.so.1

should it be otherwise ?

worker@worker:~$ roslaunch kinect2_bridge kinect2_bridge.launch
... logging to /home/worker/.ros/log/bd77c3ea-2b69-11e5-a39b-80ee73a74cf2/roslaunch-worker-2517.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://worker:45846/

SUMMARY

PARAMETERS
 * /kinect2_head_kinect2_bridge/sensor_id: 
 * /kinect2_head_kinect2_bridge/sensor_name: kinect2_head
 * /kinect2_head_points_xyzrgb_highres/queue_size: 2
 * /kinect2_head_points_xyzrgb_lowres/queue_size: 2
 * /rosdistro: indigo
 * /rosversion: 1.11.13

NODES
  /
    kinect2_head_kinect2_bridge (kinect2_bridge/kinect2_bridge)
    kinect2_head_points_xyzrgb_highres (nodelet/nodelet)
    kinect2_head_points_xyzrgb_lowres (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [2529]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to bd77c3ea-2b69-11e5-a39b-80ee73a74cf2
process[rosout-1]: started with pid [2542]
started core service [/rosout]
process[kinect2_head_kinect2_bridge-2]: started with pid [2545]
process[kinect2_head_points_xyzrgb_lowres-3]: started with pid [2546]
process[kinect2_head_points_xyzrgb_highres-4]: started with pid [2547]
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenCLDepthPacketProcessor::init] ERROR: clGetPlatformIDs(-1001)
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
[kinect2_head_kinect2_bridge-2] process has died [pid 2545, exit code -6, cmd /home/worker/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge __name:=kinect2_head_kinect2_bridge __log:=/home/worker/.ros/log/bd77c3ea-2b69-11e5-a39b-80ee73a74cf2/kinect2_head_kinect2_bridge-2.log].
log file: /home/worker/.ros/log/bd77c3ea-2b69-11e5-a39b-80ee73a74cf2/kinect2_head_kinect2_bridge-2*.log

**Comment by nanodust** [comment]
i tried rebooting, no luck. 

should i just manually point /etc/OpenCL/vendors/nvidia.icd somewhere else ? or is there a better way to fix this ?

**Comment by mmunaro** [comment]
Many times you need to repeat this step after every reboot before running tracking with Kinect v2:

 cd ~/workspace/ros/catkin/devel/lib/kinect2_bridge
 sudo ./kinect2_bridge

Does it work for you?

**Comment by nanodust** [comment]
yep - that was it ! forgot to run the bridge again. 

furthermore, the instructions as they were... one indeed has to quit ' roslaunch kinect2_bridge kinect2_bridge.launch' before starting tracking and detection... 
I've updated the instructions. 

thanks!!!
