### ISSUE TITLE
background selection disables detection... does bg subtraction work w/ kinect 2 ? 

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#49]
detection works OK (i've seen far better! trying to get it there...) but to eliminate false positives from static objects in the environment, I turn on background subtraction. 

however when I run the sensor w/ subtraction on - there are zero detections. 

does BG subtraction work with the kinect 2 ? 

this is a new clean single camera system, no in/ex/trinsic calibration yet performed, simply demonstrating system via roslaunch tracking detection_and_tracking_kinect2.launch

**Comment by mmunaro** [comment]
Yes, background subtraction works also with Kinect 2.
Could it be that you have too many flying pixels in your cloud and these points are learned as part of the background?

**Comment by nanodust** [comment]
the flying pixels issue was my suspicion... which made me think kinect2 bg subtraction is not possible. I'll try again after I do extrinsic, and will capture video & get feedback if it still doesn't work.   thanks !

**Comment by lthursdayl** [comment]
I know this is closed, but I have found that with the Kinect v2, background subtraction will work with flying pixels. The catch is that with many flying pixels the ground plane will need to be set manually for the background subtraction to work properly.
