### ISSUE TITLE
Kinect v1 Tracking

### ISSUE THREAD

**Issue by dan7em** [OpenPTrack/open_ptrack#54]
Hi,
I want to perform tracking with a single Kinect and PC, but I am having a problem with the detection_and_tracking.launch program. I used a standalone version of OpenNI in the past, but now when I installed ROS OpenNI stopped working, so I followed your advice and installed Freenect (and it's listed in my .bachrc file too). Freenect.launch works without any problem and I can see output in rviz. I performed an intrinsic calibration and finally tried to test the tracking program. However, it keeps saying that no device is connected and the rviz window is empty. When I abort it and run freenect.launch it finds my camera again. I have a feeling that it has something to do with the driver, the tracking program probably attempts to use OpenNI instead of Freenect... Even though, as I said, I explicitly set the driver to freenect in the .bachrc file. Do you have any ideas how to fix it?

**Comment by nanodust** [comment]
what does

   echo $KINECT_DRIVER

say ? 

if openni, before running OPT, make sure to

   source ~/.bashrc 

if that's not it... if it is at all possible to start on a clean installation of 14.04 w/o anything previously installed, and then follow the installation steps, 
it should work just fine.

**Comment by mmunaro** [comment]
Check also this issue, related to problems with the OpenNI driver:
https://github.com/OpenPTrack/open_ptrack/issues/19

**Comment by dan7em** [comment]
It gave me freenect...
After a lot of pain I finally decided to reboot my pc and it worked! Perhaps the old assignment was stuck somewhere in the memory. 
Now I'm on to the next step, trying to decipher Rviz output to make sure everything works before reading JSON data. When I choose either detection or tracking history it says N number of messages was received (where N > 0), but the 3D visualization window remains blank. It might be that I'm new to ROS and just haven't configured it as needed, but another thing is, when I look at the detection window I don't see any squares around humans, just the raw RGB output. Is this normal?

**Comment by dan7em** [comment]
Also, when I run it I get this in my console:

Ground plane initialization starting...
Automatic mode for ground plane estimation.
Ground plane coefficients: 0.0716385, 0.987616, 0.139582, -1.48269.

[ERROR] [1442550811.655085015]: transform exception: "world" passed to lookupTransform argument target_frame does not exist. 

Does the "automatic mode" mean that my calibration failed?

And what does the second error mean?

**Comment by mmunaro** [comment]
The ground plane estimation seems to work for you and it says that your camera is 1.48 meters above the ground (last ground plane coefficient). 
The [ERROR] you get is normal at startup, it happens only once because not all transforms between reference frames are already set.
The fact that you see no rectangles around humans in the image and no tracks in RViz is not normal.

> Does the "automatic mode" mean that my calibration failed?

The "automatic mode" for ground plane estimation is set in the yaml configuration file for people detection. It does not mean that the calibration failed. 

Which launch file are you running for tracking?
Are you following this guide?
https://github.com/OpenPTrack/open_ptrack/wiki

**Comment by dan7em** [comment]
Yes, I've been following that guide step by step. The launch file I am using is detection_and_tracking.launch in the tracking directory. But there is one additional step I had to make. When I first tried to launch the launch file ROS told me it couldn't find it. So I went to the ROS directory and saw that there were no files mentioned in the compiling script output whatsoever. I then found the launch files in ~/workspace/ros/catkin/source, so I just copied ~/workspace/ros/catkin/source/tracking into /opt/ros/indigo/share along with the other folders I found. After that ROS stopped complaining.

**Comment by mmunaro** [comment]
From your directories, it seems you did not install OpenPTrack with the installing scripts provided.
You should have a directory tree like this:
~/workspace
   -> ros
       -> catkin
           -> src (or source in your case)
               -> open_ptrack
                   -> detection
                   -> opt_calibration                   
                   -> tracking
                   -> etc.

I think this is the reason why ROS cannot find OpenPTrack launch files.

Anyway, the launch file you are launching is to perform tracking with one Kinect v1 only, without using more than one sensor and without taking into account any extrinsic calibration of the camera network.

**Comment by mmunaro** [comment]
It is not showing the indentation, this is what I meant:
~/workspace
----> ros
--------> catkin
------------> src (or source in your case)
----------------> open_ptrack
--------------------> detection
--------------------> opt_calibration                   
--------------------> tracking
--------------------> etc.

**Comment by dan7em** [comment]
I'm sorry, I totally messed up writing the directory paths... So yes, I had exactly the same tree that you showed, but it didn't work. I did install it using the scripts. So I actually moved the folders from ~/workspace/ros/catkin/src/open_ptrack/* to /opt/ros/indigo/share, and that's when it found it.
And yes, I'm using a single Kinect, connected to my main computer, running the program from the same computer.

**Comment by nanodust** [comment]
" I actually moved the folders from ~/workspace/ros/catkin/src/open_ptrack/* to /opt/ros/indigo/share, "

I've installed this system hundreds of times since project start... and I've never had to do that !  

Indeed, I just installed it on two fresh machines 3 weeks ago, worked perfectly, no issues. 

I can't recommend enough that you start with a totally clean 14.04 instance, and follow the scripts verbatim.  (Anytime something changes / doesn't work, we update the install scripts)

From that fresh state, If anything does not work, let us know!

**Comment by dan7em** [comment]
Okay guys, so I thought about what you said about the camera being 1.4 m above the ground, when it actually was more like 1.8, and I recalibrated it. Now it's tracking me just fine, so that's where the problem lied. Thanks for all the help!
Here's another thing - is it supposed to also track... a fan? I have a small black fan, 20 cm in diameter, positioned about 5 m from the camera, and it's tracking it as well for some reason.

**Comment by dan7em** [comment]
One final request. The wiki is quite vague on the topic of how json data is delivered. From what I understand the program records the whole tracking history in JSON, but that means that this data gets old with every new frame. Does this mean that there is new JSON data every fraction of a second? Or is it updated, say, once a second? I'm trying to understand how to make my program respond to immediate changes in people's positions.

**Comment by nanodust** [comment]
Glad you got it working. it can be a bit sensitive out of the box. 
You can now tune parameters for your environment. Background subtraction, haars thresholds... 
in this way you can track people, and only people :) 

the primary parameters are described in https://github.com/OpenPTrack/open_ptrack/wiki/Imager-Settings

rosrun rqt_reconfigure rqt_reconfigure allows you to make adjustments to them in realtime to see what's best, before (manually) saving the new params to the file.

**Comment by nanodust** [comment]
>From what I understand the program records the whole tracking history in JSON, 
no - it emits a new JSON object for every detection. 

if you want the entire history, you'll have to consume and store that history. 

> Does this mean that there is new JSON data every fraction of a second? 

yes

>So could you post another page there explaining how it works and what the structure of its output exactly is?

the structure of the json message is given [here](https://github.com/OpenPTrack/open_ptrack/wiki/Using%20The%20Data)

along with many examples of consumers in various languages.  

what language are you using to consume ?

**Comment by nanodust** [comment]
as you have Kinect 1 detection working, I'm closing this issue. Please open a new one if you need more help w/ UDP. meanwhile, do try some of the examples first, to get a feel for it !
