### ISSUE TITLE
Mesa SR 4500 - still functional on 'master' branch ? 

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#55]
I know we've generally been using the new Kinect v2 rather than the SR 4500 - I'm writing to verify that the current 'master' branch should still work with the SR 4500. 

I see there are recent changes removing SR 4500 as a dependency if user does not need the mesa imager. 

Is there anything new we must do (that may not be captured in installation script / documentation) to get the SR 4500 to work w/ current master branch ?

**Comment by nanodust** [comment]
also, any mention of the SR 4500 has fallen off of the 'install guide' - https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide

if we still support it, we should explicitly provide instructions for testing.

**Comment by mmunaro** [comment]
The SR4500 should still be supported as usual.
I don't have a sensor with me for testing the new features with the SR4500, but none of them should have removed the possibility to use it.
Mesa drivers are still installed by default. The dependency has been removed so that OpenPTrack can still be installed even if for some reasons the Mesa drivers are not correctly installed in the machine.

**Comment by nanodust** [comment]
Thanks ! good to know what's changed. 

unfortunately the documentation doesn't have anything about testing the mesa imager. I don't have one on-hand anymore, and I don't recall the actual launch steps...

**Comment by mmunaro** [comment]
The mesa imager is handled as the other sensors when using it in an OpenPTrack network.
You need to specify the corresponding label (sr4500) in the 'camera_network.yaml' file:
https://github.com/OpenPTrack/open_ptrack/blob/master/opt_calibration/conf/camera_network.yaml.example

Then, when you launch the 'calibration_initializer.launch' file as described in the guide
https://github.com/OpenPTrack/open_ptrack/wiki/Camera-Network-Calibration
the launch files for the imager are created: sensor_<imager_name>.launch and detection_node_<imager_name>.launch.

Thus, there is no distinction with respect to the other supported sensors, thus there is no separate guide.

If you want to try it out without any network calibration, this is the command you can launch:
roslaunch tracking detection_and_tracking_sr.launch
but (only) in this case you need to specify the correct swissranger IP in this file:
https://github.com/OpenPTrack/open_ptrack/blob/master/detection/launch/detector_depth_sr.launch

**Comment by nanodust** [comment]
thanks ! no word if they got it working yet... but this will help them.
