### ISSUE TITLE
Kinect v2 Install Error

### ISSUE THREAD

**Issue by Kelly0024** [OpenPTrack/open_ptrack#56]
Hi Matteo,
I am attemping to install the kinect2_install.sh file onto a fresh installation of 14.04. I was able to install OpenPTrack without any errors, but when I run the kinect2_install.sh I am getting this error:
[ 96%] Built target swissranger_camera_gencfg
In file included from /home/kelly/workspace/ros/catkin/src/iai_kinect2/depth_registration/src/depth_registration_opencl.cpp:24:0:
/usr/include/CL/cl.hpp: In function 'void cl::detail::fence()':
/usr/include/CL/cl.hpp:1041:38: error: '_mm_mfence' was not declared in this scope
     inline void fence() { _mm_mfence(); }
                                      ^
make[2]: *** [iai_kinect2/depth_registration/CMakeFiles/depth_registration.dir/src/depth_registration_opencl.cpp.o] Error 1
make[1]: *** [iai_kinect2/depth_registration/CMakeFiles/depth_registration.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

I did still try running rosrun kinect2_bridge kinect2_bridge. This was the error I received:
parameter:
        base_name: kinect2
           sensor: 
        fps_limit: -1
       calib_path: /home/XXX/catkin_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: opengl
     depth_device: -1
       reg_method: default
       reg_devive: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 2
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4

/home/XXX/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge: symbol lookup error: /home/XXX/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge: undefined symbol: _ZN12libfreenect220DepthPacketProcessor6ConfigC1Ev

**Comment by mmunaro** [comment]
Hi,

did you follow all the instruction reported in this guide for installing Kinect v2?
https://github.com/OpenPTrack/open_ptrack/blob/master/docs/Kinect2_installation_guide.txt

What graphic card are you using?

**Comment by lthursdayl** [comment]
Also, did you create a symlink as suggested in this link before installing the Kinect v2 library: https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide#3-install-openptrack I have found if this is not completed the Kinect v2 library will not always install properly. 

You can also refer to this link for supported GPUs: https://github.com/OpenPTrack/open_ptrack/wiki/Tested-Hardware
