### ISSUE TITLE
Deep Learning compatability

### ISSUE THREAD

**Issue by nanodust** [OpenPTrack/open_ptrack#57]
Not an OPT specific issue, just an environmental note. 

I have installed Theano and Caffe (and their dependencies) on my 'OPT Dev Box' w/ Kinect 2. 

Not for openPtrack work - but for other GPU work work. 

it's worth noting that ROS gets un-installed as a dependency (boost) is upgraded
ie - Theano works, but Caffe needs boost>1.55, and 
sudo apt-get libboost1.55-all-dev 
un-installs ROS, and thus OPT will no longer work. 

I'm going to fuss w/ this more, see if I can get OPT working along side this deep learning toolchain. 

(no i'm not using this https://www.autonomous.ai/deep-learning-robot - but would be cool if OPT was an option for those that do)

and for what it's worth, this took 2.5 days to train on the same box
https://github.com/Russell91/ReInspect
it's interesting to think of another detection layer that is perhaps trained by existing detections
however likely pure thought experiment / OPT works well as-is after calibration. 

anyway, I'll share notes if i get OPT working again post-caffe...

**Comment by nanodust** [comment]
I did not get as far with this, but it's still interesting... though I will say OPT already performs better than 'deep learning' based results like https://arxiv.org/abs/1604.07468 for example.

though it may be possible to augment & retain non-persistent IDs beyond RGB hinting.

**Comment by jburkeucla** [comment]
OPT v2 "Gnocchi" will include convolutional neural network person detection based on Darknet's Yolo and pose recognition based on an approach from CMU that uses Caffe.
