### ISSUE TITLE
Invoking "make -j8 -l8" failed

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#58]
installation process step 1-4 sem ok
step 5 is seems error but because it optional, i dont fix the error and skip step 5 and continue to step 6
step 6.1, i skip this step because i am using intel hd 4600 (i wonder is that the problem ?)
then step 6.2 i got this error : 

[ 96%] Built target kinect2_bridge
[ 96%] Built target swissranger_camera_gencfg
In file included from /home/motionserver/workspace/ros/catkin/src/pointgrey_camera_driver/pointgrey_camera_driver/src/PointGreyCamera.cpp:32:0:
/home/motionserver/workspace/ros/catkin/src/pointgrey_camera_driver/pointgrey_camera_driver/include/pointgrey_camera_driver/PointGreyCamera.h:47:36: fatal error: flycapture/FlyCapture2.h: No such file or directory
 #include "flycapture/FlyCapture2.h"
                                    ^
compilation terminated.
make[2]: *** [pointgrey_camera_driver/pointgrey_camera_driver/CMakeFiles/PointGreyCamera.dir/src/PointGreyCamera.cpp.o] Error 1
make[1]: *** [pointgrey_camera_driver/pointgrey_camera_driver/CMakeFiles/PointGreyCamera.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

dude, can you explain to me what is the error and the solution ?
edit : i am using kinect v2

**Comment by mmunaro** [comment]
The error is about the driver for PointGrey cameras, that was optional.
Since you are interested in Kinect v2, you can remove the package pointgrey_camera_driver from your ROS workspace (/home/motionserver/workspace/ros/catkin/src/) and build the rest.

**Comment by motionagus** [comment]
wow, thanks dude. i delete the pointgrey folder and fixed the error (y)

**Comment by motionagus** [comment]
dude when i test point cloud "roslaunch kinect2_bridge kinect2_bridge.launch"
i got this error :

[kinect2_head_kinect2_bridge-2] restarting process
process[kinect2_head_kinect2_bridge-2]: started with pid [26622]
Couldn't find an AF_INET address for [motionserver-H87M-D3H]
[DepthRegistration::New] OpenCL registration method not available!
[DepthRegistration::New] OpenCL registration method not available!
[OpenGLContext] failed to initialize glew for the current context!
[kinect2_head_kinect2_bridge-2] process has died [pid 26622, exit code -11, cmd /home/motionserver/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge __name:=kinect2_head_kinect2_bridge __log:=/home/motionserver/.ros/log/45ef5eea-b84b-11e5-a77b-14cc201d6ae0/kinect2_head_kinect2_bridge-2.log].
log file: /home/motionserver/.ros/log/45ef5eea-b84b-11e5-a77b-14cc201d6ae0/kinect2_head_kinect2_bridge-2*.log

is this because i skip step 6.1 ? but when i execute command " sudo apt-get install ocl-icd-opencl-dev" and finish and re execute "roslaunch kinect2_bridge kinect2_bridge.launch" the error stil same like above. can you tell me what is going on ?
