### ISSUE TITLE
OpenCL registration method not available!

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#59]
when follow step 7.1 to execute "roslaunch kinect2_bridge kinect2_bridge.launch"
i got this error : 

[kinect2_head_kinect2_bridge-2] restarting process
process[kinect2_head_kinect2_bridge-2]: started with pid [3236]
[DepthRegistration::New] OpenCL registration method not available!
[DepthRegistration::New] OpenCL registration method not available!
[OpenGLContext] failed to initialize glew for the current context!

i search in code iai github and found that is because libfreenect2 does not initialize glfw. dude
how i fix this problem ?

**Comment by motionagus** [comment]
i repeate step 1 - 6 and got new error 
output in termnal : 

[kinect2_head_kinect2_bridge-2] restarting process
process[kinect2_head_kinect2_bridge-2]: started with pid [3134]
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenGLContext] failed to initialize glew for the current context!

i still trying to figure it out...

**Comment by marketto89** [comment]
@motionagus,

currently open_ptrack requires a CUDA-capable graphic card if you want to use the Kinect v2 (see https://github.com/OpenPtrack/open_ptrack/wiki/Supported-Hardware). 

You can use OpenCL or the CPU instead of OpenGL for the packet pipeline by modifying `kinect2_bridge.cpp` inside the packet `iai_kinect2`, but it is not tested yet.

**Comment by motionagus** [comment]
@marketto89 : if i installed supported cuda graphics card, does test point cloud likely going to work ? i still dont know what kind of view i get when point cloud is work.

btw dude i actually dont understand  what you mean by using OpenCL or CPU instead of OpenGL for packet pipeline, btw what its gonna do ?

**Comment by marketto89** [comment]
Yes, if you install a supported CUDA graphic card and you follow the OpenPTrack wiki (https://github.com/OpenPTrack/open_ptrack/wiki), you should not have any problem. 

By the way, if you choose to test anyway the Intel HD4600,take care that this is an unsupported card and you could likely have problems. In this case, the first thing I would test is to change the row 154-165 of kinect2_bridge.cpp to be sure to invoke  `packetPipeline = new OpenCLPacketPipeline(deviceId)` and `depthRegLowRes = DepthRegistration::New(DepthRegistration::CPU);
    depthRegHighRes = DepthRegistration::New(DepthRegistration::CPU);`.

**Comment by motionagus** [comment]
@marketto89  i tried to change it but still didnt work. 

![screenshot from 2016-01-14 13 46 29](https://cloud.githubusercontent.com/assets/15138478/12317690/1a6a5e00-bac6-11e5-8a58-bed3fc9da17e.png)


maybe i should installed cuda supported vga. 
btw @marketto89  or @mmunaro did you know the percentage for accurate of openptrack to counting people cause as far as i know when using blob method to determine people its always not perfect.

**Comment by nanodust** [comment]
@motionagus 
>OpenCL or CPU instead of OpenGL for packet pipeline, btw what its gonna do ?

these all refer to how the Kinect 2 driver is being processed - it can be done with CPU (normal - but very intensive) or GPU (more efficient) . To use GPU one must use an SDK/Library, and that's where CUDA, OpenGL, and OpenCL come in. Each roughly do the same thing, but with different libraries. 

The only supported solution is OpenGL.   

If you're doing something other than what is on https://github.com/OpenPtrack/open_ptrack/wiki/Supported-Hardware 

such as Intel GPU or OpenCL - we can point you in the right direction , but you're on your own.

if you want a working system, stick to the supported hardware, and follow the wiki. 

If you do that, then yes, it tracks extremely well from the start. 
it can indeed be tuned so there are zero false tracks, and IDs are very persistent. 
as can be seen from the vimeo page. https://vimeo.com/channels/864928

So the percentage may not be 100%, it's very close, and far closer than any other system I've seen (though there is no other system quite like this one, and certainly not open sourced). 

Thanks for your interest in the project!
