### ISSUE TITLE
The specified source space "/home/src" does not exist

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#60]
when i repeat step from the begining, i got an error when installing kinect2_install.sh
this is output in the terminal : 

-- Installing: /usr/local/lib/libglfw.so.3.0
-- Up-to-date: /usr/local/lib/libglfw.so.3
-- Up-to-date: /usr/local/lib/libglfw.so
-- Removed runtime path from "/usr/local/lib/libglfw.so.3.0"
Cleaning
Removing the libfreenect2 folder
./kinect2_install.sh: line 41: cd: /home/workspace/ros/rosbuild: No such file or directory
./kinect2_install.sh: line 42: cd: ../catkin/src/: No such file or directory
fatal: destination path 'iai_kinect2' already exists and is not an empty directory.
Already on 'development'
Your branch is up-to-date with 'origin/development'.
Base path: /home
The specified source space "/home/src" does not exist
motionserver@motionserver-H87M-D3H:~/open_ptrack/scripts$ 

i tried execute "export ROS_WORKSPACE=/home/workspace/ros/rosbuild" output is fine but didnt fix the problem.
i think before the repead i also got this but i didnt notice and continue to test point cloud step 7 but didnt work and post issue in this https://github.com/OpenPTrack/open_ptrack/issues/59
i am new in this ros, or kinnect ubuntu things, so i dont know what going on, can you tell me the solution dude ?

**Comment by motionagus** [comment]
i change :
export ROS_WORKSPACE=/home/workspace/ros/rosbuild
to :
export ROS_WORKSPACE=/home/motionserver/workspace/ros/rosbuild
*motionserver is my pc username
and got it through step 6 without error

**Comment by lorenzznerol** [comment]
I had my src folder in another directory than the home directory. Just change your command accordingly to a path where your /src folder is really in, and the error will be gone.
