### ISSUE TITLE
error test point cloud and single camera tracking on installation step 7.1 and 7.2

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#61]
i test openkinect library libfreenect2 and got it working, display four image on test ir, rgb etc.

![screenshot from 2016-01-12 17 01 33](https://cloud.githubusercontent.com/assets/15138478/12260395/42b9cb76-b94e-11e5-94b2-71bf4314a14f.png)

but when i install libfreenect2 it create folder libfreenect2 on home directory. but whe i execute "kinect2_install.sh" step 6.2 on installation part. the folder libfreenect2 removed. then the installation is finished without error and when i execute : "roslaunch kinect2_bridge kinect2_bridge.launch"
i got error : 

[kinect2_head_kinect2_bridge-2] restarting process
process[kinect2_head_kinect2_bridge-2]: started with pid [12722]
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenGLContext] failed to initialize glew for the current context!
[kinect2_head_kinect2_bridge-2] process has died [pid 12722, exit code -11, cmd /home/motionserver/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge __name:=kinect2_head_kinect2_bridge __log:=/home/motionserver/.ros/log/4500df9c-b911-11e5-9b08-14cc201d6ae0/kinect2_head_kinect2_bridge-2.log].
log file: /home/motionserver/.ros/log/4500df9c-b911-11e5-9b08-14cc201d6ae0/kinect2_head_kinect2_bridge-2*.log

and when i execute : "rosrun rviz rviz"
i got error : 

![screenshot from 2016-01-12 16 47 14](https://cloud.githubusercontent.com/assets/15138478/12260092/46d3031e-b94c-11e5-9fe6-a0880909e406.png)

and when i execute : "roslaunch tracking detection_and_tracking_kinect2.launch" (single camera tracking)
i got this : 

![screenshot from 2016-01-12 16 33 48](https://cloud.githubusercontent.com/assets/15138478/12260108/664fdbfe-b94c-11e5-8f2c-23eac3ac6fb9.png)

can someone figuring out the solution ?

**Comment by marketto89** [comment]
@motionagus,

it seems to me that you probably should have skipped some passages in the installation guide. Anyway, if libfreenect2 works as it seems, you should fix the glew issue following this commit from the original repository of iai_kinect2 (the instruction you need are the glfwInit()  ):
https://github.com/code-iai/iai_kinect2/commit/efd26792504ffe88aae8f7f6d53698e8b4af5a8f.

Regarding the rviz error, take care that the libfreenect2 library has nothing to do with ROS so you should not need rviz. Anyway, the `rosrun` command requires a `rosmaster` running which is implicitly run by the `roslaunch` command (or you can simply run `roscore` on another terminal).

**Comment by marketto89** [comment]
see #59
