### ISSUE TITLE
X server found. dri2 connection failed!  Trying to open directly...Device open failed

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#62]
i installed nvidia gforce 750
i am using ubuntu 14.04
i follow installation step until 6.1 without error 
but when i am in step 6.2 reboot
my ubuntu wont load normally, just bios, then choose ubuntu then blank black screenn but i think the ubuntu is running it just wont display anything.
then when i am restart and choose ubuntu recovery, its start normal. i dont know what recovery do to any part of step installed in installation OpenPTrack.
then i execute :

cd ~/workspace/ros/catkin/devel/lib/kinect2_bridge
 sudo ./kinect2_bridge
 
then 

roslaunch kinect2_bridge kinect2_bridge.launch

result : 

![screenshot from 2016-01-15 15 28 43](https://cloud.githubusercontent.com/assets/15138478/12349380/df6bb5ce-bba1-11e5-8416-603dc5ab6e5a.png)

its not about opengl or glview anymore like lastime. i somewhat know the driver nvidia is the problem cause when i remove nvidia driver 352, ubuntu load fine, then i install nvidia driver 331, ubuntu wont load, and remove 331 driver ubuntu load fine.
what i already do is download and install openni manually and still not work, so any idea what is going on ? i mean can some of you explain more clearly what the error said and cause of what and solution ?

**Comment by motionagus** [comment]
update : 
nvidia driver 352 is now installed corectly on my ubuntu for geforce 750 (can even open nvidia control panel) and add user to group video.
but now i have different error than last time, device open directly is success
this is the output of the terminal : 

![screenshot from 2016-01-18 11 20 36](https://cloud.githubusercontent.com/assets/15138478/12383233/1c1f3eb0-bdd6-11e5-8c1a-e559bb0b7286.png)

**Comment by nanodust** [comment]
nvidia driver tends to over-write necessary files... 
try:
sudo apt-get install ocl-icd-opencl-dev

then reboot & try again...

**Comment by motionagus** [comment]
@nanodust  : i tried sudo apt-get install ocl-icd-opencl-dev and even sudo apt-get install --reinstall ocl-icd-opencl-dev

but the output is still same. i capture screen shoot before error, i wonder if this is related. the devices id is blank, is this a problem ?

![screenshot from 2016-01-18 13 13 01](https://cloud.githubusercontent.com/assets/15138478/12384537/995d7d38-bde5-11e5-9ad8-b11aa32314d3.png)

**Comment by motionagus** [comment]
i tried run clinfo and here the result : 

![screenshot from 2016-01-18 13 27 30](https://cloud.githubusercontent.com/assets/15138478/12384688/610bebac-bde7-11e5-9408-714713730572.png)

so its opencl the problem right ?

**Comment by motionagus** [comment]
@nanodust  : the opencl just fixed and clinfo display info of the right things. how it is fixed is by removing "beignet" to be honest i dont remember installing this package, some how its like
conflict with open cl nvidia.

 now  i execute "roslaunch kinect2_bridge kinect2_bridge.launch" , the terminal display lines of word that i think is work. then i execute "rosrun rviz rviz" but the window still not display point cloud like bellow

![screenshot from 2016-01-18 15 19 35](https://cloud.githubusercontent.com/assets/15138478/12386558/fd0e6b72-bdf8-11e5-8eae-c421f575a342.png)


then i execute "roslaunch tracking detection_and_tracking_kinect2.launch"

and display infrared with terminal like below : 

![screenshot from 2016-01-18 15 18 19](https://cloud.githubusercontent.com/assets/15138478/12386563/0971e1a0-bdf9-11e5-86cb-3d71ae7863d2.png)

![screenshot from 2016-01-18 15 24 08](https://cloud.githubusercontent.com/assets/15138478/12386568/0f3dc914-bdf9-11e5-918f-c6a88aba79ec.png)

but the rviz wont display any point cloud, : 

![screenshot from 2016-01-18 15 19 59](https://cloud.githubusercontent.com/assets/15138478/12386587/26985e76-bdf9-11e5-9bed-5aef881e0308.png)

do you have any idea what is going on ?

**Comment by mmunaro** [comment]
To see the point cloud after launching kinect2_bridge.launch, you need to do this after opening RViz:
 - set Fixed Frame as /kinect2_head_rgb_optical_frame
 - add a PointCloud2 visualization and set the topic as /kinect2_head/depth_lowres/points
as described here in the guide:
https://github.com/OpenPTrack/open_ptrack/blob/master/docs/Kinect2_installation_guide.txt#L48

**Comment by motionagus** [comment]
@mmunaro : :+1:  that's work, thankyou
@nanodust : thankyou

![screenshot from 2016-01-18 16 36 33](https://cloud.githubusercontent.com/assets/15138478/12387816/ad6f0168-be01-11e5-8687-a543296873d8.png)

now i can move to next step
