### ISSUE TITLE
how to get tracking messege single kinect v2 tracking in python

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#63]
my purpose is to do some calculating base on message tracking output single kinect traking in python.
is there any way to doing that ? cause in sample there are only a  code sample for multi sensor tracking via udp, while i only have one kinect and one computer with nvidia cuda. and when i execute "rostopic echo /tracker/track" i got warning like this : 

![screenshot from 2016-01-21 13 42 09](https://cloud.githubusercontent.com/assets/15138478/12473553/b766fa2c-c045-11e5-9db7-56bbbf2547c0.png)

what is that warning mean dude ?

what i already done is just looking at menu add component to find any topic /tracker/track and i cant find it.

**Comment by mmunaro** [comment]
The correct name of the tracking topic is /tracker/tracks_smoothed.

You can write a Python script within a ROS package for reading the tracking messages or read the data from an external application or computer.

For the latter case, the tracking output is also sent as UDP messages and can be read in Python with this sample receiver:
https://github.com/OpenPTrack/open_ptrack/blob/master/docs/assets/optreceiver.py

**Comment by motionagus** [comment]
@mmunaro :  whoah great ! thats work

![screenshot from 2016-01-21 16 33 32](https://cloud.githubusercontent.com/assets/15138478/12476573/de59b0a4-c05c-11e5-94f4-3383a415cfb8.png)

thanks dude :+1:
