### ISSUE TITLE
no devices connected

### ISSUE THREAD

**Issue by cherltte** [OpenPTrack/open_ptrack#64]
hello,

I am having hard time connecting 2 kinect2. Especially on the calibration stage.

some symptoms:
when I tried,
1. wroslaunch kinect2_bridge kinect2_bridge.launch
works(I see data comming in and infrared light on kinect2)
-> I'm assuming that there are not connection errors
2. roslaunch opt_calibration sensor_kinect_left.launch
displays "no devices connected... waiting.."
-> ?

I've followed the instruction in Troubleshooting(change to freenect and downgrade version) but nothing seems to wok for me. 
Anyone help me on this?

rcp

**Comment by motionagus** [comment]
maybe you want to try this : 

https://github.com/OpenKinect/libfreenect2

just to know if the device is working. 
i test it to test if my kinect v2 with ubuntu 14.04 working or not. and i got it working like picture bellow : 

![screenshot from 2016-01-12 17 01 33](https://cloud.githubusercontent.com/assets/15138478/12544479/fb371d7a-c36c-11e5-8b66-10bd577eb3f3.png)

**Comment by mmunaro** [comment]
So far, it is not possible to connect two Kinect v2 or a Kinect v2 and another sensor in general to the same USB bus. This is a problem of the libfreenect2 driver that OpenPTrack is using. Kinect v2 seems to block the USB bus, so that no other sensor can be connected.

**Comment by cherltte** [comment]
@motionagus @mmunaro thank you for your reply!

I've found the problem, the setting parameter was different among PCs
however, now I am facing new problem. 

I've successfully followed up until running roslaunch opt_calibration sensor_PC.launch (client) and roslaunch opt_calibration calibration_master.launch (main). 
Terminal indicates "all sensors are connected."
the next step is to show checkerboard to each kinect. I showed checkerboard to each kinect but nothing happened (the instruction says the terminal or the console will display "/PC added to the tree")

I'm assuming the global status is having an error.
in global options, fixed frame displays as "world".(I've tried others on the lists like kinect_left_ir_frame, kinect_right_link, etc, and I could only manage to work with one at a time and which still cannot detect checkerboard) 
any advice? 
I am very new to ROS, please bear with me.

@mmunaro I am using 3 PCs one each kinect for each PC.

rcp

**Comment by mmunaro** [comment]
Is your checkerboard consistent with the parameters set in the camera_network.yaml file?
https://github.com/OpenPTrack/open_ptrack/blob/master/opt_calibration/conf/camera_network.yaml.example#L38

**Comment by cherltte** [comment]
@mmunaro yes they are rows:7 cols:6 width&height: .12

**Comment by cherltte** [comment]
anyone who can help me?

**Comment by cherltte** [comment]
@mmunaro I think the problem is tf broadcasting
what should I do for tf setting? any suggestion?
