### ISSUE TITLE
error intrinsic calibration, when calibrating color

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#65]
when i execute : "rosrun kinect2_calibration kinect2_calibration record color chess4x5x0.12 -color /kinect2_head/mono/image -ir /kinect2_head/ir/image -interval 1 ~/tmp/" 
this is run fine, display crossing rainbow line then record and restore frame color in temp folder. 

![screenshot from 2016-01-22 15 32 43](https://cloud.githubusercontent.com/assets/15138478/12544251/026e70f4-c36b-11e5-8c14-a7d39e1ca696.png)

i tried to change distance, angle its still detect and record. after that i press ctr c to stop the recording color calibration prosses then remove the chess board i made from styrofoam then when i execute "rosrun kinect2_calibration kinect2_calibration calibrate color chess4x5x0.12 -color /kinect2_head/mono/image -ir /kinect2_head/ir/image -interval 1 ~/tmp/"
i got this error : 

![screenshot from 2016-01-22 15 15 24](https://cloud.githubusercontent.com/assets/15138478/12544286/5f6fae08-c36b-11e5-8860-845912151176.png)

i repeat this step numerous of time, but fail on calibrating color from the recorded frame.

i tried to skip color calibration and move to calibrating infrared. and no detection like picture bellow. changing angle, position and distance. not work either.

![screenshot from 2016-01-22 15 24 25](https://cloud.githubusercontent.com/assets/15138478/12544391/614058bc-c36c-11e5-86fe-2c39386f9006.png)

i wonder if eror is this because of lighting in the room or chessboard i made from styrofoam. 

can you lighten me dude ?

edit : this is sample frame recorded in tmp folder.

![0012_color](https://cloud.githubusercontent.com/assets/15138478/12544544/ad83e724-c36d-11e5-8ed4-427afc149e37.png)

some of them is blurry but when i delete all the blurry frame and execute calibrate color command still not working.

edit : the chessboard is not precise by mili cause it made of black 12 cm x 12 cm then stick it using double tape. and the white square is the texture of styrofoam like dragon's scales but its still white. i also wonder if this the cause.

**Comment by mmunaro** [comment]
Actually the color calibration is working for you, the error you see is an estimate of how good is the result you obtain. Indeed, you can see below the camera matrix and the distortion coefficients estimated with this procedure.
For the IR, the tape is not a good choice since it creates some stripes visible at the infrared camera.
Be sure to be able to get infrared images where the black and white square are clearly visible, similarly to what you get from the color camera.

**Comment by motionagus** [comment]
oh, i see, so my calibrating color is working actually :)
thanks dude, i need to fix chess board then.
btw i want to ask in this part https://github.com/OpenPTrack/open_ptrack/issues/48
in that issue/question actually you mention single kinect tracking also need extrinsic calibration but just ground estimation. me myself is also single kinect v2 tracking do this mean that after i finish instrinsic calibration, i move to extrinsic callibration by putting chess board on the floor and execute "rostopic pub /opt_calibration/action std_msgs/String "save" -1" ?

**Comment by mmunaro** [comment]
Yes, that's it.

**Comment by motionagus** [comment]
:+1: thank you very much dude :+1:
