### ISSUE TITLE
Help on calibration

### ISSUE THREAD

**Issue by cherltte** [OpenPTrack/open_ptrack#66]
Hi
I am trying to install ptrack and stuck for couple of days.
I need help! 

here is the system configuration:
2 PCs for 2 Kinect 2, 1 master PC
(everything sync through cat5e)

I followed every instruction and got to point where I can calibrate with checkerboard.
I can see data coming and operate each kinect at a time. but the problem is I cannot calibrate.
nothing happens if I bring checkerboard around (chekcerboard is 7 x 6 .12 size rigid)
I see there is an error regarding with tf and thus global status error like in the screen shot below,
![screenshot from 2016-01-26 17 11 51](https://cloud.githubusercontent.com/assets/12269498/12575489/2109f7a0-c450-11e5-857b-2e5d8a9b734e.png)
I figured tf is broken between two kinects where master PC can only access through one kinect at a time. like below(rqt_tf_tree screenshot),
![screenshot from 2016-01-26 17 12 27](https://cloud.githubusercontent.com/assets/12269498/12575490/210bc134-c450-11e5-9c81-a791eba0c6df.png)
How should I proceed further? 
please help me out on this

rcp

**Comment by nanodust** [comment]
The 'Transform:' status warning is not the problem - it will go away after calibration. 

The bigger problem is, I don't see either kinect topic in RVIZ. Can you browse topics, and view kinect's RGB topic (to see the video?) for example ? 

 If you were able to successfully see the Kinect topic per-host, but cannot now, verify your network.yaml (doc here https://github.com/OpenPTrack/open_ptrack/wiki/Pre-Calibration-File-Configuration#2-create-files-for-multi-sensor-calibration)

**Comment by cherltte** [comment]
@nanodust Thank you for your reply!

I am not sure what is kinect topic, but all camera RGB Mono IR etc works fine. I am attaching images.
what should I do?

regarding camera_network.yaml all three of computer share identical data(which has only two sensor PCs listed). Do master computer needs to be on the list too? for instance - pc: sMaster-server, because as you mentioned above, I thought it might be that problem. however, I've tested it with master computer and failed(rviz doesn't open).
![screenshot from 2016-01-26 19 43 21](https://cloud.githubusercontent.com/assets/12269498/12578687/e3843c04-c465-11e5-8cf2-0b8ae75821fa.png)
![screenshot from 2016-01-26 19 46 54](https://cloud.githubusercontent.com/assets/12269498/12578690/eabe994c-c465-11e5-9e9f-d19e5579acd3.png)

**Comment by nanodust** [comment]
share your camera.yaml here ?

**Comment by lthursdayl** [comment]
It would also be helpful if you share your terminal output from the roslaunch opt_calibration opt_calibration_master.launch and roslaunch opt_calibration sensor_[sensor name].launch

**Comment by cherltte** [comment]
@nanodust @lthursdayl Thanks for helping me!! This calibration process is too tough.. hope this terminal outputs and yaml file help you to understand me.

====================================Camera_network.yaml
network:
  - pc: "PC-1"
    sensors:
      - type: kinect2
        id: "kinect108"
  - pc: "PC-2"
    sensors:
      - type: kinect2
        id: "kinect209"

# Checkerboard parameters
checkerboard:
  rows: 7
  cols: 6
  cell_width: 0.12
  cell_height: 0.12
 ====================================Master Output



====================================Sensor Output
wonderlab1@IF-kinect1:~$ roslaunch opt_calibration sensor_kinect108.launch
... logging to /home/wonderlab1/.ros/log/fa5b7c4e-c50a-11e5-8ef4-c42c03233d2d/roslaunch-IF-kinect1-30014.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.0.8:51125/

SUMMARY
========

PARAMETERS
 * /kinect108_kinect2_bridge/sensor_id: 
 * /kinect108_kinect2_bridge/sensor_name: kinect108
 * /kinect108_points_xyziii/queue_size: 2
 * /rosdistro: indigo
 * /rosversion: 1.11.16

NODES
  /
    kinect108_base_link (tf/static_transform_publisher)
    kinect108_base_link1 (tf/static_transform_publisher)
    kinect108_base_link2 (tf/static_transform_publisher)
    kinect108_base_link3 (tf/static_transform_publisher)
    kinect108_broadcaster (tf/static_transform_publisher)
    kinect108_kinect2_bridge (kinect2_bridge/kinect2_bridge)
    kinect108_points_xyziii (nodelet/nodelet)

ROS_MASTER_URI=http://192.168.0.2:11311/

core service [/rosout] found
process[kinect108_base_link-1]: started with pid [30023]
process[kinect108_base_link1-2]: started with pid [30024]
process[kinect108_base_link2-3]: started with pid [30025]
process[kinect108_base_link3-4]: started with pid [30026]
process[kinect108_kinect2_bridge-5]: started with pid [30033]
process[kinect108_points_xyziii-6]: started with pid [30037]
process[kinect108_broadcaster-7]: started with pid [30041]
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenCLDepthPacketProcessor::listDevice]  devices:
  0: GeForce GTX 750 (GPU)[NVIDIA Corporation]
[OpenCLDepthPacketProcessor::init]  selected device: GeForce GTX 750 (GPU)[NVIDIA Corporation]
[Freenect2Impl] enumerating devices...
[Freenect2Impl] 10 usb devices connected
[Freenect2Impl] found valid Kinect v2 @2:7 with serial 016242652847
[Freenect2Impl] found 1 devices
Kinect2 devices found: 
  0: 016242652847 (selected)
[Freenect2DeviceImpl] opening...
[Freenect2DeviceImpl] opened

starting kinect2

[Freenect2DeviceImpl] starting...
[Freenect2DeviceImpl] ReadData0x14 response
92 bytes of raw data
0x0000:  00 00 15 00 00 00 00 00 01 00 00 00 43 c1 1f 41    ............C..A
0x0010:  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0x0020:  0a 21 33 55 c2 00 17 20 00 08 00 00 10 00 00 00    .!3U... ........
0x0030:  00 01 00 00 00 10 00 00 00 00 80 00 01 00 00 00    ................
0x0040:  31 33 00 00 00 01 04 0f 47 4d 46 36 31 31 2e 31    13......GMF611.1
0x0050:  58 00 00 00 00 00 00 00 07 00 00 00                X...........

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  1d 26 00 00                                        .&..

[Freenect2DeviceImpl] ReadStatus0x090000 response
4 bytes of raw data
0x0000:  03 26 00 00                                        .&..

[Freenect2DeviceImpl] enabling usb transfer submission...
[Freenect2DeviceImpl] submitting usb transfers...
[Freenect2DeviceImpl] started

device serial: 016242652847
device firmware: 2.3.3913.0.7

default ir camera parameters: 
fx 364.883, fy 364.883, cx 255.399, cy 206.22
k1 0.0949118, k2 -0.276687, p1 0, p2 0, k3 0.0983648

default color camera parameters: 
fx 1081.37, fy 1081.37, cx 959.5, cy 539.5

could not load calibration data from "/home/wonderlab1/workspace/ros/catkin/src/iai_kinect2/kinect2_bridge/data/016242652847". using sensor defaults.

camera parameters used:
camera matrix color:
[1081.3720703125, 0, 959.5;
  0, 1081.3720703125, 539.5;
  0, 0, 1]
distortion coefficients color:
[0, 0, 0, 0, 0]
camera matrix ir:
[364.8825073242188, 0, 255.3990936279297;
  0, 364.8825073242188, 206.2200012207031;
  0, 0, 1]
distortion coefficients ir:
[0.09491179883480072, -0.2766867876052856, 0, 0, 0.09836482256650925]
rotation:
[1, 0, 0;
  0, 1, 0;
  0, 0, 1]
translation:
[0; 0; 0]

[DepthPacketStreamParser::handleNewData] not all subsequences received 0
[DepthRegistrationOpenCL::listDevice]  devices:
  0: GeForce GTX 750 (GPU)[NVIDIA Corporation]
[DepthRegistrationOpenCL::init]  selected device: GeForce GTX 750 (GPU)[NVIDIA Corporation]
[DepthRegistrationOpenCL::listDevice]  devices:
  0: GeForce GTX 750 (GPU)[NVIDIA Corporation]
[DepthRegistrationOpenCL::init]  selected device: GeForce GTX 750 (GPU)[NVIDIA Corporation]
set process thread priority to: 19
set process thread priority to: 19
starting main loop
set process thread priority to: 19
set process thread priority to: 19
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 991
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 767
[OpenCLDepthPacketProcessor] avg. time: 5.73804ms -> ~174.275Hz
[TurboJpegRgbPacketProcessor] avg. time: 19.3939ms -> ~51.5627Hz
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 767
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 511
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 1021
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 1007
[OpenCLDepthPacketProcessor] avg. time: 5.64322ms -> ~177.204Hz
[TurboJpegRgbPacketProcessor] avg. time: 17.9253ms -> ~55.787Hz
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 959
^C[kinect108_broadcaster-7] killing on exit
[kinect108_points_xyziii-6] killing on exit
[kinect108_kinect2_bridge-5] killing on exit
[kinect108_base_link3-4] killing on exit
[kinect108_base_link2-3] killing on exit
[kinect108_base_link1-2] killing on exit
[kinect108_base_link-1] killing on exit
[Freenect2DeviceImpl] stopping...
[Freenect2DeviceImpl] disabling usb transfer submission...
[Freenect2DeviceImpl] canceling usb transfers...
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[TransferPool::submit] transfer submission disabled!
[Freenect2DeviceImpl] stopped
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] releasing usb interfaces...
[Freenect2DeviceImpl] deallocating usb transfer pools...
[Freenect2DeviceImpl] closing usb device...
[Freenect2DeviceImpl] closed
[Freenect2DeviceImpl] closing...
[Freenect2DeviceImpl] already closed, doing nothing
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by lthursdayl** [comment]
okay, before we comment on the terminal printout, your camera_network.yaml setting are incorrect.  

It should look like:

# Camera network parameters
network:
  - pc: "PC1-Example"
    sensors:
      - type: kinect1
        id: "Kinect_Left"
        serial: "A00364820345039A"
      - type: kinect1
        id: "Kinect_Right"
        serial: "A00345482325021B"

I would suggest reading over this documentation:
https://github.com/OpenPTrack/open_ptrack/wiki/Pre-Calibration-File-Configuration

You can find the Kinect 1 serial number by unplugging and replugging in the USB connection for the Kinect then running:

dmesg

this should print out the Kinect's Serial Number

**Comment by marketto89** [comment]
@lthursdayl I think that the network @cherltte is trying to calibrate is based on two different PCs each of them with a Kinect v2 attached.

If this is the case, your camera_network should be correct, but the output you have suggests me that the error could be the wrong checkerboard measurements. Double check if your checkerboard has really 7 rows, 6 cols of chess intersections and 0.12(meters) x 0.12(meters) squares. If you are not sure, provide us a checkerboard screenshot seen from one of your Kinect v2.

**Comment by cherltte** [comment]
@lthursdayl, @marketto89 is right. I am connecting 2 kinecte v2 with 2 PCs each and one master PC.

I re checked the size of the checkerboard and found square is 0.01 bigger that 0.12, but other than that everything is as instructed. here is a screenshot.
![screenshot from 2016-01-28 21 15 00](https://cloud.githubusercontent.com/assets/12269498

/12644244/e73e73fa-c604-11e5-9ebb-42c5ea79f22a.png)

any suggestion?

**Comment by marketto89** [comment]
@cherltte 

your checkerboard is actually 6 rows and 5 cols not 7x6. Fix these measurements (check also the square measurement) and everything should be fixed.

**Comment by cherltte** [comment]
@marketto89 Of course! it was 6 x5. Now it\s working! Thank you for helping me out!
