### ISSUE TITLE
after calibration on single kinect, tracking become weird and point cloud and image become round like camera 360

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#67]
this is what i did : 
1. record color : 

![screenshot from 2016-01-27 13 54 56](https://cloud.githubusercontent.com/assets/15138478/12607520/2ab9a1ac-c508-11e5-89eb-f59373e99574.png)

then calibrate color : 
i forget to capture the result of the calibrate color but its similiar to result calibrate ir bellow.

2.. record ir : 

![screenshot from 2016-01-27 13 59 44](https://cloud.githubusercontent.com/assets/15138478/12607555/77f8ab20-c508-11e5-85d3-2cd499e31256.png)

then calibrate ir result : 

![screenshot from 2016-01-27 14 02 38](https://cloud.githubusercontent.com/assets/15138478/12607569/90383d68-c508-11e5-867b-885d3f51757e.png)

3.. record sync (detecting both just fine) : 

![screenshot from 2016-01-27 14 04 55](https://cloud.githubusercontent.com/assets/15138478/12607588/b9952856-c508-11e5-9f21-7a390a4d2ff2.png)

then calibrate sync :

![screenshot from 2016-01-27 14 07 03](https://cloud.githubusercontent.com/assets/15138478/12607604/ccaea5fc-c508-11e5-873d-da7ca4dc529a.png)

4.. then i tried to run rviz with topic lowres and fixed frame kinect2_rgb_optical_frame. the image i got is like this : 

![screenshot from 2016-01-27 14 14 10](https://cloud.githubusercontent.com/assets/15138478/12607647/2938d54a-c509-11e5-9373-62af51bb60af.png)

 then i move the kinect to another room this is the view : 

![screenshot from 2016-01-27 14 16 15](https://cloud.githubusercontent.com/assets/15138478/12607671/5763312c-c509-11e5-9491-55a72348b6b9.png)

5.. then i tried to run single kinect tracking and the result is like bellow : 

![screenshot from 2016-01-27 14 21 33](https://cloud.githubusercontent.com/assets/15138478/12607727/af2c2eb8-c509-11e5-8e79-c475d3c52804.png)

6.. then i add estimation ground plane, and run single kinect tracking command at first its error something like "mising reference to ground parameter" then i move chessboard so sensor can fully view that and reexecute "rostopic pub /opt_calibration/action std_msgs/String "save" -1" for ground estimation, then run single kinect tracking command, then the error gone, somehow estimation ground parameter is right. but the result is still same and lag and detecting random thing even that random things didnt move, with the rounded image is like bellow : 

![screenshot from 2016-01-27 14 42 01](https://cloud.githubusercontent.com/assets/15138478/12607859/a0bf29f6-c50a-11e5-9a11-05f407f35670.png)

7.. i close all terminal and try to run rviz but the result is also rounded even the image is rounded, like picture bellow : 

![screenshot from 2016-01-27 14 51 27](https://cloud.githubusercontent.com/assets/15138478/12607881/cac65008-c50a-11e5-87f2-6c674ba60e05.png)

so it somehow wrong with calibration prosses the rviz is not even aligned. the questiion is when the calibration proses seems fine until finish but the result is not, then how i can fix this or what stuff i can do to calibration proses for better result ?

**Comment by motionagus** [comment]
btw is it posible to just copy your 3 file kinect2 calibration to my folder data/(kinectserial) ?

**Comment by nanodust** [comment]
i've worked w/ the system for over 2 years, never seen anything resembling your image distortion results. I'm impressed. Something is, however, very wrong. 
Note you do not *need* to intrinsically calibrate w/ a single kinect.
It will detect and track without calibration. 
Extrinsic calibration is required for N-camera setups. 
I doubt very much the kinect2 calibration copy will work. but why not try it.

**Comment by motionagus** [comment]
@nanodust then dude can you share yours :) ?

btw the problem is i want to try tracking with calibration to see if it better or not cause i did tracking without calibration but the tracking is detecting non human, something like light and laptop screen, but it also detecting human pretty well and fast, but at startup the unmoving human is not detected, but i dont know is it will detecting any little drone flying around.

**Comment by motionagus** [comment]
btw again, i want to fix that distortion problem. can you also share your recorded frame of ir, color and sync, i want to see if it because of lighting factor. cause the infrared can detect chessboard just in certain lighting, it must be shaded, if i light the room it will not detect chessboard / there not rainbow line.

**Comment by nanodust** [comment]
>hen dude can you share yours :) ?

it doesn't work like that. The reason for intrinsic calibration is to account for variances in devices (manufacturing variance, lens shifts, etc). Thus they are not portable. 

>not cause i did tracking without calibration but the tracking is detecting non human, something like light and laptop screen, 

the first approach I would've taken, out of the box, if i'm trying to improve detection on a single camera system has nothing to do with calibration at all - instead, adjusting detection parameters. You can interactively move sliders around in realtime, and find the best settings for your setup to retain maximum sensitivity via 

 rosrun rqt_reconfigure rqt_reconfigure 

more here https://github.com/OpenPTrack/open_ptrack/wiki/Tips-and-Tricks and  

as to which values, - see here https://github.com/OpenPTrack/open_ptrack/wiki/Imager-Settings
'haar_disp_ada_min_confidence' is the most dramatic parameter. 

the best way to fix distortion is to delete your intrinsic calibration files, ignore that, and do the above, just tune detection. 

Furthermore the Kinect 2 has far less variance than the Kinect 1 - so I'd submit that intrinsic calibration is not necessary for what you're after. Better to tune detection and wait to calibrate until you absolutely need to set ground plane & transform.

**Comment by motionagus** [comment]
i see, i will try that.
but i have question @nanodust  dude, in issue 48 matteo dude said that detection is not affected by extrinsic calibration of ground estimate with check board, but the tracking is affected then how is it ?

**Comment by nanodust** [comment]
>detection is not affected by extrinsic calibration of ground estimate with check board,
that is consistent with what i'm saying. 
recall there are two orthogonal processes in openPtrack: 

a) detection 
b) tracking 

tune detection to be as good as possible, before focusing on tracking.

**Comment by motionagus** [comment]
@nanodust  dude : i already follow your suggestion, i change haar_disp_ada_min_confidence:  from 2.0 until -2.0 then i change ground_based_people_detection_min_confidence then i change min and max person height. there are certainly significant change to the detection like more sensitive. but there are not fix any problem of false detection, the laptop, door and some change of light / maybe ghost still detected. like image bellow i capture when detecting door.

![screenshot from 2016-01-29 14 17 08](https://cloud.githubusercontent.com/assets/15138478/12669902/a7cde31c-c696-11e5-8aa5-409f1fbea6e5.png)

 but when i enable background subtracktion and apply denoising, there no false detection. btw is there any way to seet background for subtraction manually, but i also have consent that there are might someone who put a things the whole day and because of background subtraction that thigns is detected the whole day also. 

there also problem i was wondering. when the tracking running or roslaunch kinect2_bridge running there are this output in the terminal : 

[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 959

i wonder if this normal or not. but when i doing searching on google , i found this 

![screenshot from 2016-01-29 13 27 49](https://cloud.githubusercontent.com/assets/15138478/12670012/77a20546-c697-11e5-8aab-e138ba153258.png)

the lighting here is not that bright like museum, i wonder if this also the cause of distortion image when calibrating intrinsic.

but there also one more issue, sometime the id of tracked people while moving is disapear for awhile like 20 - one second more. then id deleted by sistem and the same person give the new diferent id of tracking. but most of time the id of tracked ppl disapear for a little while and still have the same id. how is it @nanodust ? cause my goal is also on consistent in id of tracking beside solid ppl tracking.
