### ISSUE TITLE
when running single kinect tracking the detection is less and less by hour passed and then the tracking stopped by its self.

### ISSUE THREAD

**Issue by motionagus** [OpenPTrack/open_ptrack#69]
i running single tracking but after about a hour, the detection stopping by its self and all window close and the terminal display something like this : 

![screenshot from 2016-02-02 14 42 53](https://cloud.githubusercontent.com/assets/15138478/12743688/fd119700-c9c1-11e5-8f49-5bc5c7d7876c.png)

i am curious the running tracking again util three time but its happen 3 times, can someone explain why this happen ?

**Comment by nanodust** [comment]
Hm. 
while my guess is the kinect driver crashing
perhaps post the full logs to pastebin so we can see them.

**Comment by motionagus** [comment]
sorry for late reply @nanodust , yes its likely the kinect driver or some ros component.
it happen after i uninstall ros by purge and all ros dependency by autoremove, then reinstall ros.
but i already fresh install and it not happen again

**Comment by nanodust** [comment]
glad to hear it !
