### ISSUE TITLE
Jetson Step 9a: unable to 'sudo make install'

### ISSUE THREAD

**Issue by redfood** [OpenPTrack/open_ptrack#70]
I've been (slowly) going through all the installation steps on the Jetson.  Everything has been going well until the last part of step 9a: `sudo make install`

The error message I get is:
`make: *** No rule to make target `install'.  Stop.`

I think I'm in the correct directory (`~/libfreenect2/examples/protonect`)

Any suggestions and/or workarounds?

**Comment by nanodust** [comment]
hmm. i have not tried it on Jetson yet! i will give it a shot this weekend...

**Comment by marketto89** [comment]
@redfood,

If you followed the wiki here: https://github.com/OpenPTrack/open_ptrack/wiki/Jetson-TK1-Installation
you should be in `~/libfreenect/examples/protonect/build`.

Let us know if you have further problems!

**Comment by redfood** [comment]
Great thanks.  I took a break from the installation process then when I went to pick up from where I left off I missed the `&& cd build`.  Sorry to trouble you.
