### ISSUE TITLE
Error at end of step j in jetson installation. 

### ISSUE THREAD

**Issue by redfood** [OpenPTrack/open_ptrack#71]
I'm at the end of step J in the jetson installation:
`rostopic hz /kinect2_head/depth_ir/points`
For which I get the following error:
`ERROR: Unable to communicate with master!`

Everything else seemed to work up until this point.

**Comment by marketto89** [comment]
@redfood,

the `rostopic hz /kinect2_head/depth_ir/points` is able to provide you the framerate of the messages streamed in the topic `/kinect2_head/depth_ir/points`.

Your error means there is no one who is publishing that topic. So, you have to run it only while
 `roslaunch kinect2_bridge kinect2_bridge_ir.launch` 
is running in another terminal. If you stop this roslaunch command before running the `rostopic` one you should see the error you report.

**Comment by redfood** [comment]
Great thank you.
 
When when I run 'rostopic hz /kinect2_head/depth_ir/points' I get framrates a bit over 21 FPS which is great.  However, the other process running `roslaunch kinect2_bridge kinect2_bridge_ir.launch` continually reports errors which look like this:

```
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[DepthPacketStreamParser::handleNewData] subpacket too large
[DepthPacketStreamParser::handleNewData] subpacket incomplete (needed 298496 received 264704)
[DepthPacketStreamParser::handleNewData] packet loss (sequence expected 1602.0 actual 1601.2)
[DepthPacketStreamParser::handleNewData] packet loss (sequence expected 1602.0 actual 1601.3)
[DepthPacketStreamParser::handleNewData] packet loss (sequence expected 1602.0 actual 1601.4)
[DepthPacketStreamParser::handleNewData] packet loss (sequence expected 1602.0 actual 1601.5)
[DepthPacketStreamParser::handleNewData] packet loss (sequence expected 1602.0 actual 1601.6)
[DepthPacketStreamParser::handleNewData] packet loss (sequence expected 1602.0 actual 1601.7)
[DepthPacketStreamParser::handleNewData] packet loss (sequence expected 1602.0 actual 1601.8)
[DepthPacketStreamParser::handleNewData] packet loss (sequence expected 1602.0 actual 1601.9)
[DepthPacketStreamParser::handleNewData] skipping depth packet because processor is not ready
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[DepthPacketStreamParser::handleNewData] skipping depth packet because processor is not ready
```

Is this normal/to be expected or does something give to be done?

**Comment by marketto89** [comment]
Don't worry, if the framerates are as you said you should not have problems about the errors you mentioned.
