### ISSUE TITLE
Will openPtrack work with multiple IP cameras / a network of solely 2D imagers, or are stereocameras required?

### ISSUE THREAD

**Issue by Pturner645** [OpenPTrack/open_ptrack#75]
Are stereocameras (depth information) needed for the tracking or will it still work using only IP camera inputs?

**Comment by mmunaro** [comment]
Hi, 
depth and color (or grayscale) information is needed by OpenPTrack.
At the moment of writing, it works with:
- Kinect v1 (structured-light sensor + RGB camera)
- Kinect v2 (Time-of-Flight camera + RGB camera)
- Mesa SwissRanger SR4500 (Time-of-Flight camera, the grayscale information is derived from the intensity image provided by the ToF sensor)
- stereo cameras built with PointGrey cameras

**Comment by Pturner645** [comment]
Thank you!
