### ISSUE TITLE
install error  step3   package ceres

### ISSUE THREAD

**Issue by itsZheng** [OpenPTrack/open_ptrack#78]
the question is:
from wiki install guide - https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide
1. ok
2. ok
3. error
![error-ceres](https://cloud.githubusercontent.com/assets/17996726/14036701/baf975c6-f276-11e5-9ae9-00e3d9dafcb1.png)
CMake Error at calibration_toolkit/calibration_common/CMakeLists.txt:23 (FIND_PACKAGE):
  By not providing "FindCeres.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Ceres", but
  CMake did not find one.

  Could not find a package configuration file provided by "Ceres" with any of
  the following names:

    CeresConfig.cmake
    ceres-config.cmake

  Add the installation prefix of "Ceres" to CMAKE_PREFIX_PATH or set
  "Ceres_DIR" to a directory containing one of the above files.  If "Ceres"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/administrator/workspace/ros/catkin/build/CMakeFiles/CMakeOutput.log".
See also "/home/administrator/workspace/ros/catkin/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
administrator@ubuntu:~/open_ptrack/scripts$

**Comment by facetohard** [comment]
Well, I meet this problem too. To solve it ,you should install Ceres.

**Comment by facetohard** [comment]
Search "Ceres" and follow the instruction.

**Comment by itsZheng** [comment]
can you explain in more detail

**Comment by itsZheng** [comment]
how to install Ceres???
I am in China,I can't search google.

**Comment by facetohard** [comment]
You can use bing to search .
http://ceres-solver.org/
follow this turtorials to install Ceres.

**Comment by facetohard** [comment]
Sorry, follow this 
http://ceres-solver.org/building.html

**Comment by facetohard** [comment]
You can use bing to search Ceres, follow this site to install Ceres
http://ceres-solver.org/building.html

**Comment by itsZheng** [comment]
![ceres-clone](https://cloud.githubusercontent.com/assets/17996726/14072519/e12a4de0-f4f3-11e5-8bd7-8600590205f7.png)
unable to  access  ‘https://ceres-solver.googlesource.com/ceres-solver’.
I am in China,I can't search google, is that a problem?

**Comment by facetohard** [comment]
I am in china too.
Have you read the site i paste before.
You install Ceres before you do ./opentrack_install.sh, and then it will put "unable to access" but continue.

**Comment by itsZheng** [comment]
yes,i read the site .
where should i put the ceres-solver-1.11.0.tar.gz file, 
I want to install ceres together with the workspace

**Comment by facetohard** [comment]
After you installed, the header files and lib files will add your path , and when you install opentrack, it will find it automatically.

**Comment by itsZheng** [comment]
Thank you so much!!!

**Comment by itsZheng** [comment]
@facetohard 
 I have some questions that need your help.
 can you tell me your contact information?
Thank you very much of your help and i will waiting for your reply.
