### ISSUE TITLE
Configuration file location

### ISSUE THREAD

**Issue by jburkeucla** [OpenPTrack/open_ptrack#79]
Runtime configuration files should not be loaded from src directories, shouldn't they?  can we have a build/conf or conf directory rather than have them buried under src?  Or is this the ROS way?

**Comment by mmunaro** [comment]
We followed the ROS way to have a conf folder in every ROS package. 
The configuration files are within these folders.
The structure of the folders in ROS is:

~/workspace/ros/catkin/src/<package_name>/conf
~/workspace/ros/catkin/src/<package_name>/include
~/workspace/ros/catkin/src/<package_name>/src
etc.
