### ISSUE TITLE
Kinect v2 point cloud in a RViz

### ISSUE THREAD

**Issue by shuyangyue** [OpenPTrack/open_ptrack#85]
I think everything is ok before 6.4. When I tpye 

> roslaunch kinect2_bridge kinect2_bridge.launch

the result is
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 767
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[TurboJpegRgbPacketProcessor] avg. time: 19.7204ms -> ~50.7089Hz
[OpenCLDepthPacketProcessor] avg. time: 3.38143ms -> ~295.733Hz
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 511
[TurboJpegRgbPacketProcessor] avg. time: 21.6571ms -> ~46.1741Hz
[OpenCLDepthPacketProcessor] avg. time: 2.72201ms -> ~367.376Hz
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
[RgbPacketStreamParser::handleNewData] skipping rgb packet!
`
what's the reason of so many skipping rgb packet?

Then, I type

> rosrun rviz rviz

and replace the "map" with "kinect2_head_rgb_optical_frame". But I have no point cloud.

The rviz shows:
Global Status: Warn
        Fixed frame:No tf data. Actual error: Fixed Frame [kinect2_head_rgb_optical_frame] does not exist

What's wrong with me? Help~

**Comment by itsZheng** [comment]
I have the same problem. Please let me know if you solve this.

**Comment by nanodust** [comment]
'skipping rgb packet' to me sounds like a resource constraint. USB, CPU - I can't say. 

blindly, it sounds to me like a Kinect 2/360 driver issue. specifically, low bandwidth. The Kinect 2 uses nearly all USB 3.0 bandwidth; a problem I experienced frequently was poor USB 3.0 support by motherboard manufacturers. What this meant is that the Kinect would simply not work on some USB 3.0 motherboards due to low USB 3.0 throughput. This was a known issue, far beyond our work w/ OPT. In order to be absolutely certain a given hardware configuration works, I'd install windows + Kinect SDK & run 'test' tool to ensure 30 fps via USB. At least then hardware was ruled out as I'd then get the linux driver to work. 

I can't say this is exactly your problem - only that it's worth looking at.

**Comment by itsZheng** [comment]
this is my problem:

[TurboJpegRgbPacketProcessor::doProcess] Failed to decompress rgb image! TurboJPEG error: 'Invalid JPEG file structure: two SOI markers'
[OpenCLDepthPacketProcessor] avg. time: 2.7905ms -> ~358.358Hz
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 511
[TurboJpegRgbPacketProcessor] avg. time: 15.7634ms -> ~63.4379Hz
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 511
[OpenCLDepthPacketProcessor] avg. time: 2.77313ms -> ~360.604Hz
[TurboJpegRgbPacketProcessor] avg. time: 15.1326ms -> ~66.0824Hz
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] image data too short!
[DepthPacketStreamParser::handleNewData] not all subsequences received 895
[OpenCLDepthPacketProcessor] avg. time: 2.7745ms -> ~360.425Hz
[TurboJpegRgbPacketProcessor] avg. time: 14.8165ms -> ~67.4924Hz
[OpenCLDepthPacketProcessor] avg. time: 2.7636ms -> ~361.847Hz
[TurboJpegRgbPacketProcessor] avg. time: 14.4641ms -> ~69.1365Hz
[OpenCLDepthPacketProcessor] avg. time: 2.7617ms -> ~362.095Hz
[TurboJpegRgbPacketProcessor] avg. time: 13.4689ms -> ~74.2449Hz

**Comment by marketto89** [comment]
@shuyangyue  & @itsZheng 

Seeing some `[RgbPacketStreamParser::handleNewData] skipping rgb packet!
` or `[DepthPacketStreamParser::handleNewData] image data too short!
` is quite normal. 
It could be a major concern if you see __a lot of them__ in the sense that these messages are so many that you are not able to see any `avg. time: Xms -> ~YHz` in the terminal output.

Given this, the output you posted seems to be ok for me. Now a couple of questions:
- Did you install OpenPTrack completely, or are you stuck where you are testing the Kinect v2?
- Which computer are you using? If you __are not__ using a Jetson the correct frame id to be put in RVIZ as Fixed frame is __kinect2_head_ir_optical_frame__ not kinect2_head_rgb_optical_frame.
- While kinect2_bridge is running you should be able to see if the ROS topic are filled correctly. In another terminal type `rostopic hz /kinect2_head/depth_ir/points` to see if there are point cloud published.

Let us know if this fixes your problem.

**Comment by itsZheng** [comment]
hi,
1.I don't know if i install OpenPTrack completely,I see 100%.
      from wiki install guide - https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide
          1. ok
          2. ok
          3.fail---------------------------------------solve  #78 
                     I see 100%,I am not sure.
![openptrack-install](https://cloud.githubusercontent.com/assets/17996726/14518164/bffdbeca-0247-11e6-8872-2f633dac4074.png)
      
[install-openptrack.txt](https://github.com/OpenPTrack/open_ptrack/files/218451/install-openptrack.txt)

          4. n/a (not using kinect 1)
          5. n/a (not using PG)
          6. Kinect V2    6.1 OK     6.2 fail---solve  #45      6.3 Reboot     6.4 ok
          7. test    
               7.1Test Point Cloud:
                 roslaunch kinect2_bridge kinect2_bridge.launch
                         seems ok, just few 'image data too short'.
                 rosrun rviz rviz
                replace the "map" with "kinect2_head_ir_optical_frame". But I have no point  cloud.
                      The rviz shows:
                         Global Status: Warn
      Fixed frame:No tf data. Actual error: Fixed Frame [kinect2_head_ir_optical_frame] does not exist

2.My computer:
  Intel core i7-4770K cpu @3.5GHz x 8
  16GB of RAM
  NVidia GeForce GTX760 

  camera: XBOX  ONE
 I am not using a Jetson.  

3.I  can't see the ROS topic.
   administrator@ubuntu:~$ rostopic hz /kinect2_head/depth_ir/points
WARNING: topic [/kinect2_head/depth_ir/points] does not appear to be published yet

**Comment by lthursdayl** [comment]
To correct this issue you need to run in a separate window:

roslaunch kinect2_bridge kinect2_bridge.launch

then 

 rostopic hz /kinect2_head/depth_lowres/points

**Comment by itsZheng** [comment]
yes, I already did this  in different  terminal

**Comment by itsZheng** [comment]
![topic](https://cloud.githubusercontent.com/assets/17996726/14548360/cc9e968a-02e8-11e6-9a46-7f707f7d16de.png)

**Comment by itsZheng** [comment]
I use wubi.exe to  install ubuntu, there is also a win7  in my computer. 
Is that a problem?

**Comment by itsZheng** [comment]
I type     rostopic  list -v
can see the topic list 

administrator@ubuntu:~$ rostopic list -v

Published topics:
 * /kinect2_head/depth/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/ir/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/depth_rect/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/depth_lowres/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/ir_rect_eq/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/ir/image/compressed [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/rgb/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/rgb_rect/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/ir_rect_eq/image/compressed [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/rgb_lowres/image/compressed [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/depth_rect/image/compressedDepth [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/mono_lowres/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/mono_rect/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/ir/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/mono_rect/image/compressed [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/mono_rect/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/depth_rect/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/rgb/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/depth_highres/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/mono/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/depth_lowres/points [sensor_msgs/PointCloud2] 1 publisher    ------
 * /kinect2_head/mono_lowres/image/compressed [sensor_msgs/CompressedImage] 1 publisher
 * /turtle1/cmd_vel [geometry_msgs/Twist] 1 publisher
 * /kinect2_head/ir_rect/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/rgb/image/compressed [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/depth_highres/image/compressedDepth [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/rgb_rect/image/compressed [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/ir_rect_eq/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/depth/image/compressedDepth [sensor_msgs/CompressedImage] 1 publisher
 * /rosout [rosgraph_msgs/Log] 5 publishers
 * /kinect2_head/mono/image/compressed [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/mono/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/ir_rect/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/depth_lowres/image/compressedDepth [sensor_msgs/CompressedImage] 1 publisher
 * /rosout_agg [rosgraph_msgs/Log] 1 publisher
 * /kinect2_head/depth_lowres/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/depth/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/rgb_lowres/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/rgb_lowres/camera_info [sensor_msgs/CameraInfo] 1 publisher
 * /kinect2_head/rgb_rect/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/ir_rect/image/compressed [sensor_msgs/CompressedImage] 1 publisher
 * /kinect2_head/depth_highres/image [sensor_msgs/Image] 1 publisher
 * /kinect2_head/depth_highres/points [sensor_msgs/PointCloud2] 1 publisher
 * /kinect2_head/mono_lowres/image [sensor_msgs/Image] 1 publisher

Subscribed topics:
 * /rosout [rosgraph_msgs/Log] 1 subscriber

administrator@ubuntu:~$

**Comment by itsZheng** [comment]
I have topic  ' /kinect2_head/depth_lowres/points', 
but I don't have topic '/kinect2_head/depth_ir/points'

administrator@ubuntu:~$ rostopic hz /kinect2_head/depth_lowres/points
subscribed to [/kinect2_head/depth_lowres/points]
average rate: 30.899
	min: 0.020s max: 0.035s std dev: 0.00293s window: 23
average rate: 30.345
	min: 0.020s max: 0.036s std dev: 0.00212s window: 53
average rate: 30.217
	min: 0.020s max: 0.036s std dev: 0.00177s window: 83
average rate: 30.168
	min: 0.020s max: 0.036s std dev: 0.00159s window: 113
average rate: 30.126
	min: 0.020s max: 0.036s std dev: 0.00154s window: 143
average rate: 30.101
	min: 0.020s max: 0.036s std dev: 0.00149s window: 173
average rate: 30.095
	min: 0.020s max: 0.036s std dev: 0.00143s window: 203
average rate: 30.084
	min: 0.020s max: 0.036s std dev: 0.00138s window: 233
average rate: 30.071
	min: 0.020s max: 0.036s std dev: 0.00133s window: 263
average rate: 30.065
	min: 0.020s max: 0.036s std dev: 0.00129s window: 293
average rate: 30.060
	min: 0.020s max: 0.036s std dev: 0.00125s window: 323
average rate: 30.052
	min: 0.020s max: 0.038s std dev: 0.00139s window: 353
average rate: 30.050
	min: 0.020s max: 0.038s std dev: 0.00136s window: 383
average rate: 30.046
	min: 0.020s max: 0.038s std dev: 0.00133s window: 413
average rate: 30.043
	min: 0.020s max: 0.038s std dev: 0.00132s window: 443
average rate: 30.038
	min: 0.020s max: 0.038s std dev: 0.00130s window: 473


the correct frame id to be put in RVIZ as Fixed frame is kinect2_head_ir_optical_frame or ???

**Comment by mmunaro** [comment]
There are two launch files:

kinect2_bridge.launch 
- it creates /kinect2_head/depth/points with the point cloud filled with RGB color
- it has the frame_id kinect2_head_rgb_optical_frame

kinect2_bridge_ir.launch 
- it creates /kinect2_head/depth_ir/points with the point cloud filled with infrared information
- it has the frame_id kinect2_head_ir_optical_frame

Thus, it depends on which one you launch.

**Comment by itsZheng** [comment]
kinect2_bridge_ir.launch

I type

rosrun rviz rviz
and replace the "map" with "kinect2_head_ir_optical_frame". But I have no point cloud.

The rviz shows:
Global Status: Warn
Fixed frame:No tf data. Actual error: Fixed Frame [kinect2_head_ir_optical_frame] does not exist

What's wrong with me? Help~

**Comment by itsZheng** [comment]
There are two launch files:

kinect2_bridge.launch
it creates      /kinect2_head/depth_lowres/points      and      /kinect2_head/depth_highres/points 

kinect2_bridge_ir.launch
it creates       /kinect2_head/depth_ir/points  

what's wrong?

**Comment by mmunaro** [comment]
Kinect v2 is working since you can get point clouds with color.

Which branch are you using? (roscd open_ptrack && git branch)

**Comment by itsZheng** [comment]
I Clone OpenPTrack repository from GitHub.

**Comment by itsZheng** [comment]
from wiki install guide - https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide

**Comment by itsZheng** [comment]
git clone https://github.com/OpenPTrack/open_ptrack.git
