### ISSUE TITLE
[open_ptrack/opt_calibration/CMakeFiles/opt_calibration.dir/src/opt_calibration.cpp.o] Error 4

### ISSUE THREAD

**Issue by tofighi** [OpenPTrack/open_ptrack#91]
Got error in calibration software which couldn't compile. I followed exactly what is written in the document for installing on Jetson TK1.

Following installation tutorial, got a bug in section "k" that don't have currently any idea how to solve it:

https://github.com/OpenPTrack/open_ptrack/wiki/Jetson-TK1-Installation
After running the last command, CatkinJ1 :
k. Install OpenPTrack:

cd /home/ubuntu/workspace/ros/catkin/src
git clone https://github.com/OpenPTrack/open_ptrack
cd open_ptrack
git checkout jetson-dev
cd scripts
chmod +x *
./calibration_toolkit_install.sh
cd /home/ubuntu/workspace/ros/catkin/
catkin_make --pkg calibration_msgs
catkin_make --pkg opt_msgs
**CatkinJ1**

[ 88%] Building CXX object open_ptrack/opt_calibration/CMakeFiles/opt_define_reference_frame.dir/src/opt_define_reference_frame.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
make[2]: **\* [open_ptrack/opt_calibration/CMakeFiles/opt_define_reference_frame.dir/src/opt_calibration.cpp.o] Error 4
make[2]: **\* Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
make[2]: **\* [open_ptrack/opt_calibration/CMakeFiles/opt_calibration.dir/src/opt_calibration.cpp.o] Error 4
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.
make[2]: **\* [open_ptrack/opt_calibration/CMakeFiles/opt_calibration.dir/src/ros_device.cpp.o] Error 4
make[1]: **\* [open_ptrack/opt_calibration/CMakeFiles/opt_calibration.dir/all] Error 2
make[1]: **\* [open_ptrack/opt_calibration/CMakeFiles/opt_define_reference_frame.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by marketto89** [comment]
Are you sure you run `CatkinJ1` instead of `Catkin`? From your error, it seems that you run the latter or that your `CatkinJ1` script has not been installed properly.  

Anyway, if `CatkinJ1` does not work, you can simply type:
`cd /home/ubuntu/workspace/ros/catkin/`
`catkin_make --pkg calibration_msgs`
`catkin_make --pkg opt_msgs`
`catkin_make -j1 -l1`

Let us know if this fix your issue.

**Comment by jburkeucla** [comment]
Abandoned issue / closed.
