### ISSUE TITLE
Issue with installation : Running  roslaunch kinect2_bridge kinect2_bridge.launch results in the following error.

### ISSUE THREAD

**Issue by apavani** [OpenPTrack/open_ptrack#92]
I am trying to get openPtrack running on a virtualbox installation of ubuntu 14.04, on my macbook pro which has a Nvidia GT 750M

I could successfully get through till step 6.3 on the [installation page](https://github.com/OpenPTrack/open_ptrack/wiki/Installation-Guide)

## Issue 1:
When I try to run
**sudo ./kinect2_bridge**
 
It throws the following error:
```
modprobe: ERROR: could not insert 'nvidia_340': No such device
[FATAL] [1462566793.468747674]: ROS_MASTER_URI is not defined in the environment. Either type the following or (preferrably) add this to your ~/.bashrc file in order set up your local machine as a ROS master:

export ROS_MASTER_URI=http://localhost:11311

then, type 'roscore' in another shell to actually launch the master program.
```

Step 6.4 mentions that this error is normal. However I see an additional line in that error:
**modprobe: ERROR: could not insert 'nvidia_340': No such device**

Is this normal as well?

## Issue 2:
Further, if I continue to step 7.1
Running  **roslaunch kinect2_bridge kinect2_bridge.launch** results in the following error which repeats infinitely.
Can someone point out what am I doing wrong here?

```
 ... logging to /home/adarsh/.ros/log/243e1a4c-13c8-11e6-8e70-080027a2a360/roslaunch-adarsh-VirtualBox-2303.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://adarsh-VirtualBox:45441/

SUMMARY
========

PARAMETERS
 * /kinect2_head_kinect2_bridge/sensor_id: 
 * /kinect2_head_kinect2_bridge/sensor_name: kinect2_head
 * /kinect2_head_points_xyzrgb_highres/queue_size: 2
 * /kinect2_head_points_xyzrgb_lowres/queue_size: 2
 * /rosdistro: indigo
 * /rosversion: 1.11.19

NODES
  /
    kinect2_head_kinect2_bridge (kinect2_bridge/kinect2_bridge)
    kinect2_head_points_xyzrgb_highres (nodelet/nodelet)
    kinect2_head_points_xyzrgb_lowres (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [2315]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 243e1a4c-13c8-11e6-8e70-080027a2a360
process[rosout-1]: started with pid [2328]
started core service [/rosout]
process[kinect2_head_kinect2_bridge-2]: started with pid [2331]
process[kinect2_head_points_xyzrgb_lowres-3]: started with pid [2346]
process[kinect2_head_points_xyzrgb_highres-4]: started with pid [2347]
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenCLDepthPacketProcessor::init] ERROR: clGetPlatformIDs(-1001)
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
[kinect2_head_kinect2_bridge-2] process has died [pid 2331, exit code -6, cmd /home/adarsh/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge __name:=kinect2_head_kinect2_bridge __log:=/home/adarsh/.ros/log/243e1a4c-13c8-11e6-8e70-080027a2a360/kinect2_head_kinect2_bridge-2.log].
log file: /home/adarsh/.ros/log/243e1a4c-13c8-11e6-8e70-080027a2a360/kinect2_head_kinect2_bridge-2*.log
[kinect2_head_kinect2_bridge-2] restarting process
process[kinect2_head_kinect2_bridge-2]: started with pid [2397]
[DepthRegistration::New] Using OpenCL registration method!
[DepthRegistration::New] Using OpenCL registration method!
[OpenCLDepthPacketProcessor::init] ERROR: clGetPlatformIDs(-1001)
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
[kinect2_head_kinect2_bridge-2] process has died [pid 2397, exit code -6, cmd /home/adarsh/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge __name:=kinect2_head_kinect2_bridge __log:=/home/adarsh/.ros/log/243e1a4c-13c8-11e6-8e70-080027a2a360/kinect2_head_kinect2_bridge-2.log].
log file: /home/adarsh/.ros/log/243e1a4c-13c8-11e6-8e70-080027a2a360/kinect2_head_kinect2_bridge-2*.log
[kinect2_head_kinect2_bridge-2] restarting process
```

**Comment by nanodust** [comment]
Is it even possible to get direct access to the GPU from VirtualBox? I would not expect so. Perhaps it is with effort. Meanwhile the lack of the module In your logs...

**Comment by apavani** [comment]
I did read up some more if my GPU can be passed through to virtualbox, and it seems like it is not possible to do so. At least not straightforward enough to do so.
So, from what I understand, it is perhaps a better idea to start a fresh installation of Ubuntu on actual hardware and restart the installation process on a new computer.

**Comment by nanodust** [comment]
I agree, i've tried to do GPU via virtualbox before, I could never seem to get Virtualbox to do so. Docker works (for theano / tensorflow at least), can pass in GPU devices at startup, so theoretically that would work for OpenPTrack - tho I don't think we've tried.  
Meanwhile, yes, only physical hardware is supported, not virtualization. 
If you want to stay on your laptop, use Ubuntu via Bootcamp, and that should work (provided the mac usb 3 chipset has full support/bandwidth in Ubuntu). Otherwise, yes, a new computer w/ specs per https://github.com/OpenPtrack/open_ptrack/wiki/Supported-Hardware will certainly work.
