### ISSUE TITLE
rviz process dies while running roslaunch tracking detection_and_tracking.launch

### ISSUE THREAD

**Issue by apavani** [OpenPTrack/open_ptrack#94]
I'm running openPtrack on NVidia Jetson TK1
I'm running Kinect v1 (Instrinsic Calibration)
When I run `roslaunch tracking detection_and_tracking.launch` I see the following error:

```
[rviz-32] process has died [pid 7263, exit code -11, cmd /opt/ros/indigo/lib/rviz/rviz -d /home/ubuntu/workspace/ros/catkin/src/open_ptrack/tracking/conf/tracking.rviz __name:=rviz __log:=/home/ubuntu/.ros/log/24733346-1713-11e6-9483-00044b491812/rviz-32.log].
log file: /home/ubuntu/.ros/log/24733346-1713-11e6-9483-00044b491812/rviz-32*.log
```

After this error, the process then continues and opens a completely gray "Detection" window and the following message shows up in terminal in a continuous loop:
`No valid frame. Move the camera to a better position...`

I'm guessing this is an issue with rviz crashing before the "Detection" window opens.
When I run `rosrun rviz rviz` it shows nothing but a single line of error:
`Segmentation Fault`

I've tried various ways to fix rviz, but, I just can't seem to get rid of the segmentation fault error. Can someone please help me resolve this issue.

**Comment by igierard** [comment]
I work with @apavani we realized that you can't run intrinsic calibration on the TK1. We also realized that it's probably not a good idea (maybe impossible) to try and run a TK1 as the ROS master. This second part should probably be reflected in the docs.

**Comment by lthursdayl** [comment]
This is a very good point. You are correct you cannot run intrinsic calibration on the TK1 and you cannot run the master processes on the TK1 or TX1. I have updated the documentation to reflect this. 

It is also worth noting that intrinsic calibration is not a requirement, and intrinsic calibration with the Kinect v2 does not significantly enhance the reliability of tracking. Intrinsic calibration is really only necessary for the Kinect v1.

**Comment by lthursdayl** [comment]
Link to updated documentation: https://github.com/OpenPTrack/open_ptrack/wiki/Jetson-TK1-Installation
