### ISSUE TITLE
Invoking "make -j4 -l4" failed

### ISSUE THREAD

**Issue by randydevitt** [OpenPTrack/open_ptrack#98]
While attempting to do Kinect v2 setup after following all other steps, the issues "make -j4 -l4 appears after every attempt

`####
####
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target _calibration_msgs_generate_messages_check_deps_SetOmnicameraInfo
[  0%] [  0%] Built target _calibration_msgs_generate_messages_check_deps_CheckerboardMsg
Built target _calibration_msgs_generate_messages_check_deps_OmnicameraInfo
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target _calibration_msgs_generate_messages_check_deps_CheckerboardArray
[  0%] Built target std_msgs_generate_messages_cpp
[  9%] Built target bayes
[  9%] Built target sensor_msgs_generate_messages_py
[  9%] [ 10%] Built target geometry_msgs_generate_messages_py
Built target depth_registration
[ 10%] Built target _opt_msgs_generate_messages_check_deps_CalibrationStatus
[ 10%] Built target _opt_msgs_generate_messages_check_deps_HumanEntries
[ 10%] Built target _opt_msgs_generate_messages_check_deps_Detection
[ 10%] Built target _opt_msgs_generate_messages_check_deps_TrackArray
[ 10%] Built target _opt_msgs_generate_messages_check_deps_DetectionArray
[ 10%] Built target _opt_msgs_generate_messages_check_deps_OPTSensor
[ 10%] Built target _opt_msgs_generate_messages_check_deps_HumanEntry
[ 10%] Built target _opt_msgs_generate_messages_check_deps_RoiRect
[ 10%] Built target _opt_msgs_generate_messages_check_deps_BoundingBox2D
[ 10%] Built target _opt_msgs_generate_messages_check_deps_OPTTransform
[ 10%] Built target _opt_msgs_generate_messages_check_deps_BoundingBox3D
[ 10%] Built target _opt_msgs_generate_messages_check_deps_Rois
[ 10%] [ 10%] Built target _opt_msgs_generate_messages_check_deps_IDArray
Built target sensor_msgs_generate_messages_cpp
[ 10%] Built target geometry_msgs_generate_messages_cpp
[ 10%] [ 10%] Built target sensor_msgs_generate_messages_lisp
Built target geometry_msgs_generate_messages_lisp
[ 12%] Built target roi_msgs
[ 12%] [ 12%] Built target json
Built target _opt_msgs_generate_messages_check_deps_Track
[ 13%] Built target opt_utils
[ 16%] [ 16%] Built target udp_listener
Built target freenect_camera_gencfg
Linking CXX executable /home/randy/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge
[ 17%] Built target kinect2_calibration
[ 18%] Built target viewer
[ 21%] Built target calibration_algorithms
[ 23%] Built target detection_gencfg
[ 26%] Built target calibration_common
[ 28%] Built target haar_disp_ada
[ 29%] Generating dynamic reconfigure files from cfg/SwissRanger.cfg: /home/randy/workspace/ros/catkin/devel/include/swissranger_camera/SwissRangerConfig.h /home/randy/workspace/ros/catkin/devel/lib/python2.7/dist-packages/swissranger_camera/cfg/SwissRangerConfig.py
[ 30%] Built target tracking_gencfg
[ 30%] Built target swissranger_utility
[ 35%] Built target calibration_msgs_generate_messages_py
[ 38%] Built target calibration_msgs_generate_messages_lisp
[ 41%] Built target calibration_msgs_generate_messages_cpp
[ 53%] Built target opt_msgs_generate_messages_py
[ 64%] Built target opt_msgs_generate_messages_cpp
[ 75%] Built target opt_msgs_generate_messages_lisp
[ 76%] Built target roi_viewer
[ 78%] Built target ros2udp_converter
[ 79%] Built target freenect_node
[ 79%] Built target freenect_nodelet
[ 79%] Built target calibration_msgs_generate_messages
[ 81%] Built target detection
[ 81%] Built target opt_msgs_generate_messages
[ 81%] Built target HaarDispAda174
[ 82%] Built target HaarDispAda174_sr
[ 83%] Built target ground_based_people_detector
[ 84%] Built target ground_based_people_detector_sr
[ 87%] Built target opt_calibration
[ 90%] Built target opt_calibration_refinement
[ 91%] Built target stereo_publisher
[ 94%] CMakeFiles/kinect2_bridge.dir/src/kinect2_bridge.cpp.o: In function `Kinect2Bridge::Kinect2Bridge(std::string, double, bool, int, int)':
kinect2_bridge.cpp:(.text._ZN13Kinect2BridgeC2ESsdbii[_ZN13Kinect2BridgeC5ESsdbii]+0x440): undefined reference to `libfreenect2::Freenect2::Freenect2(void*)'
kinect2_bridge.cpp:(.text._ZN13Kinect2BridgeC2ESsdbii[_ZN13Kinect2BridgeC5ESsdbii]+0x835): undefined reference to `libfreenect2::OpenGLPacketPipeline::OpenGLPacketPipeline(bool)'
kinect2_bridge.cpp:(.text._ZN13Kinect2BridgeC2ESsdbii[_ZN13Kinect2BridgeC5ESsdbii]+0xa03): undefined reference to `libfreenect2::Freenect2::~Freenect2()'
CMakeFiles/kinect2_bridge.dir/src/kinect2_bridge.cpp.o: In function `Kinect2Bridge::init(std::string const&, std::string const&, int, float, float)':
kinect2_bridge.cpp:(.text._ZN13Kinect2Bridge4initERKSsS1_iff[_ZN13Kinect2Bridge4initERKSsS1_iff]+0x70): undefined reference to `libfreenect2::Freenect2::enumerateDevices()'
kinect2_bridge.cpp:(.text._ZN13Kinect2Bridge4initERKSsS1_iff[_ZN13Kinect2Bridge4initERKSsS1_iff]+0xd8): undefined reference to `libfreenect2::Freenect2::getDefaultDeviceSerialNumber()'
kinect2_bridge.cpp:(.text._ZN13Kinect2Bridge4initERKSsS1_iff[_ZN13Kinect2Bridge4initERKSsS1_iff]+0x151): undefined reference to `libfreenect2::Freenect2::getDeviceSerialNumber(int)'
kinect2_bridge.cpp:(.text._ZN13Kinect2Bridge4initERKSsS1_iff[_ZN13Kinect2Bridge4initERKSsS1_iff]+0x2a0): undefined reference to `libfreenect2::DepthPacketProcessor::Config::Config()'
kinect2_bridge.cpp:(.text._ZN13Kinect2Bridge4initERKSsS1_iff[_ZN13Kinect2Bridge4initERKSsS1_iff]+0x32a): undefined reference to `libfreenect2::Freenect2::openDevice(std::string const&, libfreenect2::PacketPipeline const*)'
kinect2_bridge.cpp:(.text._ZN13Kinect2Bridge4initERKSsS1_iff[_ZN13Kinect2Bridge4initERKSsS1_iff]+0x38b): undefined reference to `libfreenect2::SyncMultiFrameListener::SyncMultiFrameListener(unsigned int)'
CMakeFiles/kinect2_bridge.dir/src/kinect2_bridge.cpp.o: In function `Kinect2Bridge::run()':
kinect2_bridge.cpp:(.text._ZN13Kinect2Bridge3runEv[_ZN13Kinect2Bridge3runEv]+0x79a): undefined reference to `libfreenect2::SyncMultiFrameListener::waitForNewFrame(std::map<libfreenect2::Frame::Type, libfreenect2::Frame*, std::less<libfreenect2::Frame::Type>, std::allocator<std::pair<libfreenect2::Frame::Type const, libfreenect2::Frame*> > >&, int)'
kinect2_bridge.cpp:(.text._ZN13Kinect2Bridge3runEv[_ZN13Kinect2Bridge3runEv]+0x7dc): undefined reference to `libfreenect2::SyncMultiFrameListener::release(std::map<libfreenect2::Frame::Type, libfreenect2::Frame*, std::less<libfreenect2::Frame::Type>, std::allocator<std::pair<libfreenect2::Frame::Type const, libfreenect2::Frame*> > >&)'
kinect2_bridge.cpp:(.text._ZN13Kinect2Bridge3runEv[_ZN13Kinect2Bridge3runEv]+0xa5c): undefined reference to `libfreenect2::SyncMultiFrameListener::release(std::map<libfreenect2::Frame::Type, libfreenect2::Frame*, std::less<libfreenect2::Frame::Type>, std::allocator<std::pair<libfreenect2::Frame::Type const, libfreenect2::Frame*> > >&)'
CMakeFiles/kinect2_bridge.dir/src/kinect2_bridge.cpp.o: In function `Kinect2Bridge::~Kinect2Bridge()':
kinect2_bridge.cpp:(.text._ZN13Kinect2BridgeD2Ev[_ZN13Kinect2BridgeD5Ev]+0xbc): undefined reference to `libfreenect2::Freenect2::~Freenect2()'
collect2: error: ld returned 1 exit status
Built target opt_define_reference_frame
make[2]: *** [/home/randy/workspace/ros/catkin/devel/lib/kinect2_bridge/kinect2_bridge] Error 1
make[1]: *** [iai_kinect2/kinect2_bridge/CMakeFiles/kinect2_bridge.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Built target tracking
Generating reconfiguration files for SwissRanger in swissranger_camera
[ 97%] Built target swissranger_camera_gencfg
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`

**Comment by nanodust** [comment]
What is your target host?

**Comment by randydevitt** [comment]
Intel i7-5500U CPU
Intel HD graphics 5500 Broadwell GT2
Running ubuntu 14.04 LTS\

**Comment by randydevitt** [comment]
Guessing issue would be lack of CUDA gpu
